### ISSUE TITLE
Mac app is not trusted

### ISSUE THREAD

**Issue by janhoy** [MuhammedKalkan/OpenLens#1]
The mac `.dmg` package can easily be installed by dropping the app into `/Applications`, but then most users won't be able to run it due to lack of trusted signature. Is there a way for the GitHub action to pick up some credential for a Mac developer during build?

**Comment by MuhammedKalkan** [comment]
It seems it is possible to produce a signed package, however i suspect it needs developer account.
Example : https://localazy.com/blog/how-to-automatically-sign-macos-apps-using-github-actions

**Comment by janhoy** [comment]
Do you have a Mac? If not, I could probably help with the cert.

**Comment by janhoy** [comment]
I have an Apple dev account, currently investigating the steps involved. If you are willing to grant me maintainer access to this repo, I can try to add my certificate as a github secret and test the flow in a new branch.

**Comment by MuhammedKalkan** [comment]
Sure, check inv

**Comment by jkroepke** [comment]
@MuhammedKalkan I can also provide a signature through @xavierLowmiller apple developer Account. Good point to move forward here since its blocking the M1 builds here.

**Comment by MuhammedKalkan** [comment]
> @MuhammedKalkan I can also provide a signature through @xavierLowmiller apple developer Account. Good point to move forward here since its blocking the M1 builds here.

That would be the fastest solution right now. @janhoy tried the same approach but cant saw it through i  guess. if you can make a PR after signing and confirming, we can merge back here
