### ISSUE TITLE
scoop.sh support

### ISSUE THREAD

**Issue by ludoo0d0a** [MuhammedKalkan/OpenLens#10]
Please provide scoop.sh installer support

like Lens https://github.com/ScoopInstaller/Extras/blob/47e79f9ea4/bucket/lens.json

**Comment by AndrewSav** [comment]
@ludoo0d0a IMO it has to be done on scoop side, not here.

**Comment by carlreid** [comment]
Opened an issue on scoop side: https://github.com/ScoopInstaller/Extras/issues/9177
