### ISSUE TITLE
Bug in the resources buttons after update to v6.3.0

### ISSUE THREAD

**Issue by weyderfs** [MuhammedKalkan/OpenLens#100]
## TL & DR

1. After update to version `v6.3.0` the OpenLens start with gray clean screen, don't load side menu or k8s resources, it's necessary reload the application sometimes then starts to work. 
2. When you open a _pod_ the buttons: `Attatch to Pod`, `Pod Shell` and `Pod Logs` didn't showed...
![image](https://user-images.githubusercontent.com/1542315/212159241-c4d506c9-7fed-43bb-9fa9-cd3cdd725225.png)

## Workaround

- Rollback to the version `v6.2.5`.

**Comment by MathiasVandePol** [comment]
https://github.com/MuhammedKalkan/OpenLens#extensions
