### ISSUE TITLE
Tag alpha/beta/... as pre-release

### ISSUE THREAD

**Issue by smarek** [MuhammedKalkan/OpenLens#105]
Hi, thanks a bunch for your effort here

Could you just, for each release that is not stable, mark it as "pre-release" in github release edit?

See how it could look like here: https://github.com/OK-DMR/Hytera_Homebrew_Bridge/releases

Thank you a lot
Cheers!

**Comment by MuhammedKalkan** [comment]
Not fetching pre-release marked releases from original repo. It is not a great approach to check names for that purpose. 
So issue is main repo is not tagging them. That is where this needs to be resolved
