### ISSUE TITLE
Can we bundle QoL "out of tree" extensions?

### ISSUE THREAD

**Issue by AndrewSav** [MuhammedKalkan/OpenLens#107]
[Apparently](https://github.com/lensapp/lens/issues/6857#issuecomment-1386696136) viewing logs with OpenLens is now out of tree extension for some reason. As per link above people reported that it works if the extension is installed separately. Can we bundle the extension with the rest of OpenLens since it seems illogical to go backwards?

**Comment by alebcay** [comment]
See also https://github.com/lensapp/lens/issues/6855 requesting upstream document how to included desired extensions as bundled (in-tree) extensions.

**Comment by AndrewSav** [comment]
@MuhammedKalkan was this done? If so can you link PR/commit please?

**Comment by MuhammedKalkan** [comment]
@alebcay is following this on the linked issue at Lens repo. No need another issue here

**Comment by AndrewSav** [comment]
@MuhammedKalkan as far as I understand the linked issue is about _documentation_. This issue is about actually implementing this here. Does this make sense?

**Comment by MuhammedKalkan** [comment]
Nope not only that, he wants to know how to. I have already asked him here if we could bundle extensions. https://github.com/MuhammedKalkan/OpenLens/issues/83#issuecomment-1368496742

If someone has an idea or can do it , PRs are always welcome.

**Comment by AndrewSav** [comment]
Right, so what you are saying is that we do not know how to that yet. Can we may be keep the issue open until the time we do, since we obviously have not solved it yet? Thanks!

**Comment by jkroepke** [comment]
The main issue here is that we are not aware of how to bundle them. This repository has the strategy to run a build based on unmodified source (build scripts are part of the sources). A side from that, there is no offical source for the out of tree extensions yet and I would not depend agaist other 3rd party repositories.

**Comment by AndrewSav** [comment]
> The main issue here is that we are not aware of how to bundle them.

That is understood, I hope that one way or another someone figures that out.

>  I would not depend agaist other 3rd party repositories

Unfortunately, the reality is that Lens started removing functionality (viewing logs? really?) from the main source tree so they could charge for it. It is probably just the first removal but not last. If we do not figure out how to bundle third party plugins, this installation will become less and less useful as they remove more features. I've spoken with a few users and for most of them not being able to view logs in Lens reduces the usefulness of the tool severely. A few more removal like this and there will be no point using OpenLens anymore, that's my concern.

**Comment by ebbypeter** [comment]
With the removal of "core" capabilities, I am wondering if we need to pivot the discussion to fork or even split from OpenLens.

**Comment by jkroepke** [comment]
This OpenLens repo will not [the long term solution](https://github.com/MuhammedKalkan/OpenLens/issues/83#issuecomment-1368496742) here, Something like clone and patch build scripts is cat and mouse situation. Since they convert OpenLens to an npm package, they may remove the scripts for the distributions builds anyways in future. 

> A few more removal like this and there will be no point using OpenLens anymore, that's my concern.

Yes, so we are back to k9s.

And we are not aware of javascript. If some changes on the extensions are needed, no one is able to maintain it. Thats a good reason for keeping the extensions out of tree.

Fork is the way to go, But the project feels huge. I would be hart to maintain it. [LibreLens](https://github.com/LibreLens/lens) already died. Long term way would be a complete alternative to Lens OR buy one license, if you stay with it.

**Comment by marafa-sugarcrm** [comment]
readme was updated to inform users how to install the missing extensions https://github.com/MuhammedKalkan/OpenLens#extensions 

this can be closed
