### ISSUE TITLE
Error: "getting credentials: exec: executable kubectl not found"

### ISSUE THREAD

**Issue by MachineLearningIsEasy** [MuhammedKalkan/OpenLens#109]
HI!
I have problems with connection to cluster via OpenLens.

<img width="1728" alt="Снимок экрана 2023-01-18 в 16 39 17" src="https://user-images.githubusercontent.com/54454330/213187180-e10834ad-d942-4347-83b4-2d2c16d2c5d2.png">

macos, OpenLens 6.3.0,

 kubectl get ns   - works good

**Comment by MuhammedKalkan** [comment]
can you try with beta.9

**Comment by jkroepke** [comment]
@MuhammedKalkan beta9 builds for windows are broken..

See. logs

```
open-lens:   • file source doesn't exist  from=D:\a\OpenLens\OpenLens\lens\packages\open-lens\binaries\client\windows\x64\kubectl.exe
open-lens:   • file source doesn't exist  from=D:\a\OpenLens\OpenLens\lens\packages\open-lens\binaries\client\windows\x64\lens-k8s-proxy.exe
open-lens:   • file source doesn't exist  from=D:\a\OpenLens\OpenLens\lens\packages\open-lens\binaries\client\windows\x64\helm.exe
```

**Comment by jkroepke** [comment]
Should be fixed by beta12

**Comment by jkroepke** [comment]
Its fixed by beta12, but beta12 is not buildable on windows.

**Comment by MuhammedKalkan** [comment]
It just gets stuck.

**Comment by MuhammedKalkan** [comment]
> > It just gets stuck.
> 
> Any how long or when it will be available?

Building now, download and try when its done

**Comment by jkroepke** [comment]
beta13 seems availible now
