### ISSUE TITLE
openlens black taskbar icon almost not visible in dark mode on windows 10

### ISSUE THREAD

**Issue by luckyluc74** [MuhammedKalkan/OpenLens#11]
First of all great job creating openlens build!

This is how openlens icon looks link in windows 10 dark mode
![image](https://user-images.githubusercontent.com/6342858/175888101-651be68c-3ca4-4077-acff-a19640914ce6.png)

Would be nice if icon would be better visible in dark mode :)

**Comment by MuhammedKalkan** [comment]
Thanks for the feedback, however this repo is not actually a fork but a build mechanism. You should open this issue on the main repo. Please refer to Readme
