### ISSUE TITLE
OpenLens: 6.3.0 after successful login to a cluster Blank Page

### ISSUE THREAD

**Issue by ekimov** [MuhammedKalkan/OpenLens#111]
MAC M1: 12.6.1 (21G217)
OpenLens: 6.3.0
Extension API: 6.3.0
Electron: 19.1.9
Chrome: 102.0.5005.167
Node: 16.14.2

Issue: OpenLens: 6.3.0 after successful login to a cluster Blank Page

StepsToReproduce:

1. Add cluster to the context
2. Identify cluster in the list
3. Connect
4. Connection Successful

Expected result: Navigate to the Cluster Overview page

Actual result: Blank screen
![image](https://user-images.githubusercontent.com/6378321/213411396-fa0609ae-0dcc-4dbf-bd33-ebbb8b545be3.png)

**Comment by lenalebt** [comment]
Happens for me as well, but not for my colleagues. I tried throwing away all configs, but that did not help.

I'm currently working around by falling back to a mixture of octant, CLI usage etc - works, but not nice. Any ideas where this might come from?

**Comment by lenalebt** [comment]
Updating to 6.4.0-alpha3 solves the issue for me :-)

**Comment by msts1906** [comment]
Downgrading to 6.2.0 works too

**Comment by asoliman** [comment]
how do I downgrade to 6.2.5?
