### ISSUE TITLE
OpenLens with choco install: Error - hashes do not match

### ISSUE THREAD

**Issue by igorquintaes** [MuhammedKalkan/OpenLens#119]
Both commands written in [README.md](https://github.com/MuhammedKalkan/OpenLens/blob/main/README.md) leads into packages with mismatcheds hashes. 

Using `choco install -y openlens` targets 6.3.0 version, that is already known to have different hashes.
Using `choco install -y openlens --pre` targets _wrongly_ 6.4.0-beta9 version, that has different hashes too.

![image](https://user-images.githubusercontent.com/10831729/216040854-335a4af5-1b59-4ffe-a167-1c6dc4ea534a.png)

It also a know error using brew, based on closed issues #88 and #80. So, could I sugest to keep an issue open while readme commands don't work? Would be easier to people know that it is a current and tracked error - and keeping in mind that using `--ignore-checksums` always is not a good practice.

A current workaround is targeting latest beta package or a previous openlens version with a correct hash.
Example: `choco install openlens --version=6.4.0-beta10 --pre`

**Comment by MuhammedKalkan** [comment]
6.4.0 should be ok.
