### ISSUE TITLE
extensions support

### ISSUE THREAD

**Issue by raphaelauv** [MuhammedKalkan/OpenLens#12]
thanks for this repo !

why openlens is not compatible with the extensions ?

![Screenshot from 2022-07-28 18-41-15](https://user-images.githubusercontent.com/10202690/181592223-6d8e8d21-1b55-4fb1-bccb-67bae3aacd13.png)

Thanks

**Comment by MuhammedKalkan** [comment]
Extension owner may need to update his version for the 6.0.0 Lens

**Comment by raphaelauv** [comment]
thanks
