### ISSUE TITLE
EKS cluster connexion : failed to initialize proxyexec plugin

### ISSUE THREAD

**Issue by Awot83** [MuhammedKalkan/OpenLens#120]
### Discussed in https://github.com/MuhammedKalkan/OpenLens/discussions/118

<div type='discussions-op-text'>

<sup>Originally posted by **Awot83** February  1, 2023</sup>
Hello, 
i try to connect to my EKS cluster on AWS  with OpenLens-6.4.0-alpha.4 on windows 

but i am stuck with this error : 
i have already updated the AWS CLI on my windows with :
`aws eks update-kubeconfig --name XXXXXX  --region eu-west-1 --profile XXXXXXX`
and it seems ok :
`Updated context arn:aws:eks:eu-west-1:XXXXXXXXX:cluster/XXXXXXXXXX in C:\Users\XXXXXXXX\.kube\config`

message error i get when i try to connect to the cluster with openLens :

```
F0201 10:32:45.601973 20848 main.go:82] failed to initialize proxyexec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"

goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
C:/Users/runneradmin/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:860 +0x8a
k8s.io/klog/v2.(*loggingT).output(0x318ff40, 0x3, 0x0, 0xc000229110, 0x1, {0x2955de7, 0x20}, 0x3190e20, 0x0)
C:/Users/runneradmin/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:825 +0x686
k8s.io/klog/v2.(*loggingT).printDepth(0x318ff40, 0x0, 0x0, {0x0, 0x0}, 0x0, {0xc000166660, 0x2, 0x2})
C:/Users/runneradmin/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:608 +0x1c7
k8s.io/klog/v2.(*loggingT).print(...)
C:/Users/runneradmin/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:590
k8s.io/klog/v2.Fatal(...)
C:/Users/runneradmin/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:1490
main.main()
D:/a/lens-k8s-proxy/lens-k8s-proxy/main.go:82 +0x725

goroutine 53 [syscall]:
os/signal.signal_recv()
C:/hostedtoolcache/windows/go/1.17.13/x64/src/runtime/sigqueue.go:169 +0x98
os/signal.loop()
C:/hostedtoolcache/windows/go/1.17.13/x64/src/os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
C:/hostedtoolcache/windows/go/1.17.13/x64/src/os/signal/signal.go:151 +0x2c

proxy exited with code: 255
```

also please note that : 
- this openlens works fine with an other local cluster
- from the same computer in can use AWS CLI to test "aws sts get-caller-identity" (so the EKS Cluster is reachable) 

Could you help me understand the issue here ? 
thanks</div>

**Comment by jkroepke** [comment]
6.4.0 bundels kubectl 1.24 by default.

Reading https://github.com/aws/aws-cli/issues/6920, your aws cli version is outdated. Update your aws cli and re-run `aws eks update-kubeconfig cmd`"

**Comment by Awot83** [comment]
hello, 
i did it : 
`aws eks update-kubeconfig --name XXXXXX --region eu-west-1 --profile default`
i get:
`Updated context arn:aws:eks:eu-west-XXXXXXXX:cluster/XXXXXXX in C:\Users\XXXXXXX\.kube\config`
>> this should confim the update of the kubconfig ?

still get the same error on openLens
`F0201 10:32:45.601973 20848 main.go:82] failed to initialize proxyexec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1" .. `

also tried with Lens 
i have : 
```
Oops, something went wrong.
Error: read ECONNRESET
```
then 
`Kubeconfig user entry is using deprecated API version client.authentication.k8s.io/v1alpha1. Run 'aws eks update-kubeconfig' to update.`
then 
`Unknown error has occurred`

also my CLI version is  : aws-cli/2.9.19 Python/3.9.11 Windows/10 exe/AMD64 prompt/off

thanks

**Comment by jkroepke** [comment]
Looks like, its ans problem an AWS side. I guess you expect the error without lens, using the lastest kubectl version.

You may should report the error here https://github.com/aws/aws-cli
