### ISSUE TITLE
Cluster connected but no details

### ISSUE THREAD

**Issue by Akshay1181** [MuhammedKalkan/OpenLens#121]
### Discussed in https://github.com/MuhammedKalkan/OpenLens/discussions/98

<div type='discussions-op-text'>

<sup>Originally posted by **TaraBrownSmith** January 12, 2023</sup>
I'm new to OpenLens, having previously used LENS. I installed with scoop. The install appears to be successful however, once connected to my cluster, there are no details. I'm seeing zero pods, deployments, daemon sets, etc. What configuration options should I review? Thanks in advance for your assistance.

OpenLens: 6.3.0
Extension API: 6.3.0
Electron: 19.1.9
Chrome: 102.0.5005.167
Node: 16.14.2</div>

**Comment by seilorjunior** [comment]
I am having the same issue with this version

**Comment by Akshay1181** [comment]
Which version should I use for windows?
Recommend the most stable version.

Regards,
Akshay Jain

**Comment by Akshay1181** [comment]
Hi @seilorjunior 

Here is the workaround you can follow atleast on windows machine:
1. Uninstall the existing openlens , also manually delete directory: \AppData\Local\Programs\OpenLens
2. Delete this as well : \AppData\Local\open-lens-updater
3. Re-install openlens [v6.2.5](https://github.com/MuhammedKalkan/OpenLens/releases/tag/v6.2.5)

It seems cache is causing this issue, while first time installing, sometime cluster is not getting registered properly.

It worked for me😀,

**Comment by modioko** [comment]
> Hi @seilorjunior
> 
> Here is the workaround you can follow atleast on windows machine:
> 
> 1. Uninstall the existing openlens , also manually delete directory: \AppData\Local\Programs\OpenLens
> 2. Delete this as well : \AppData\Local\open-lens-updater
> 3. Re-install openlens [v6.2.5](https://github.com/MuhammedKalkan/OpenLens/releases/tag/v6.2.5)
> 
> It seems cache is causing this issue, while first time installing, sometime cluster is not getting registered properly.
> 
> It worked for me😀,

This worked for me. 
Thanks you!

**Comment by jkroepke** [comment]
@Akshay1181 you could also press CMD or CTRL + R while using 6.3.0

**Comment by jasonstitt** [comment]
I'm also seeing a blank pane for every newly connected cluster on a Mac with:

OpenLens: 6.3.0
Extension API: 6.3.0
Electron: 19.1.9
Chrome: 102.0.5005.167
Node: 16.14.2

Reinstall, including clearing the application support folder, didn't fix it.

I see this was closed - is this fixed in 6.4.0?

**Comment by jkroepke** [comment]
> I see this was closed 

its close, since repo is not the development repo.
