### ISSUE TITLE
Black screen after connecting to a cluster

### ISSUE THREAD

**Issue by luandrea** [MuhammedKalkan/OpenLens#126]
Hi all,
I got a black screen after I succesfully connect to a cluster in the Catalog page.

I'm on Windows 10 and OpenLens 6.3.0

**Comment by luandrea** [comment]
In the log file I found this errors:

`warn: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:10 InvalidGrant error, reset Lens state and set connected=false... invalid_grant (Offline user session not found) {"stack":"Error: invalid_grant (Offline user session not found)\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718800)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
info: [LENS-SPACES-EXTENSION]: (from:resetSpaceSyncer) Clearing spaces/k8sClusters...
warn: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:10 InvalidGrant error, reset Lens state and set connected=false... invalid_grant (Offline user session not found) {"stack":"Error: invalid_grant (Offline user session not found)\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718800)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
info: [LENS-SPACES-EXTENSION]: (from:resetSpaceSyncer) Clearing spaces/k8sClusters...
warn: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:11 InvalidGrant error, reset Lens state and set connected=false... invalid_grant (Offline user session not found) {"stack":"Error: invalid_grant (Offline user session not found)\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718800)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
info: [LENS-SPACES-EXTENSION]: (from:resetSpaceSyncer) Clearing spaces/k8sClusters...
warn: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:11 InvalidGrant error, reset Lens state and set connected=false... invalid_grant (Offline user session not found) {"stack":"Error: invalid_grant (Offline user session not found)\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718800)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
info: [LENS-SPACES-EXTENSION]: (from:resetSpaceSyncer) Clearing spaces/k8sClusters...
warn: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:11 InvalidGrant error, reset Lens state and set connected=false... invalid_grant (Offline user session not found) {"stack":"Error: invalid_grant (Offline user session not found)\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718800)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
info: [LENS-SPACES-EXTENSION]: (from:resetSpaceSyncer) Clearing spaces/k8sClusters...
warn: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:11 InvalidGrant error, reset Lens state and set connected=false... invalid_grant (Offline user session not found) {"stack":"Error: invalid_grant (Offline user session not found)\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718800)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
info: [LENS-SPACES-EXTENSION]: (from:resetSpaceSyncer) Clearing spaces/k8sClusters...
warn: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:11 InvalidGrant error, reset Lens state and set connected=false... invalid_grant (Offline user session not found) {"stack":"Error: invalid_grant (Offline user session not found)\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718800)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
info: [LENS-SPACES-EXTENSION]: (from:resetSpaceSyncer) Clearing spaces/k8sClusters...
warn: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:13 InvalidGrant error, reset Lens state and set connected=false... invalid_grant (Offline user session not found) {"stack":"Error: invalid_grant (Offline user session not found)\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718800)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
info: [LENS-SPACES-EXTENSION]: (from:resetSpaceSyncer) Clearing spaces/k8sClusters...
warn: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:13 InvalidGrant error, reset Lens state and set connected=false... invalid_grant (Offline user session not found) {"stack":"Error: invalid_grant (Offline user session not found)\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718800)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
info: [LENS-SPACES-EXTENSION]: (from:resetSpaceSyncer) Clearing spaces/k8sClusters...
warn: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:14 InvalidGrant error, reset Lens state and set connected=false... invalid_grant (Offline user session not found) {"stack":"Error: invalid_grant (Offline user session not found)\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718800)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
info: [LENS-SPACES-EXTENSION]: (from:resetSpaceSyncer) Clearing spaces/k8sClusters...
warn: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:14 InvalidGrant error, reset Lens state and set connected=false... invalid_grant (Offline user session not found) {"stack":"Error: invalid_grant (Offline user session not found)\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718800)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
info: [LENS-SPACES-EXTENSION]: (from:resetSpaceSyncer) Clearing spaces/k8sClusters...
warn: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:15 InvalidGrant error, reset Lens state and set connected=false... invalid_grant (Offline user session not found) {"stack":"Error: invalid_grant (Offline user session not found)\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718800)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
info: [LENS-SPACES-EXTENSION]: (from:resetSpaceSyncer) Clearing spaces/k8sClusters...
warn: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:18 InvalidGrant error, reset Lens state and set connected=false... invalid_grant (Offline user session not found) {"stack":"Error: invalid_grant (Offline user session not found)\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718800)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
info: [LENS-SPACES-EXTENSION]: (from:resetSpaceSyncer) Clearing spaces/k8sClusters...
warn: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:18 InvalidGrant error, reset Lens state and set connected=false... invalid_grant (Offline user session not found) {"stack":"Error: invalid_grant (Offline user session not found)\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718800)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
info: [LENS-SPACES-EXTENSION]: (from:resetSpaceSyncer) Clearing spaces/k8sClusters...
warn: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:21 InvalidGrant error, reset Lens state and set connected=false... invalid_grant (Offline user session not found) {"stack":"Error: invalid_grant (Offline user session not found)\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718800)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
info: [LENS-SPACES-EXTENSION]: (from:resetSpaceSyncer) Clearing spaces/k8sClusters...
warn: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:25 InvalidGrant error, reset Lens state and set connected=false... invalid_grant (Offline user session not found) {"stack":"Error: invalid_grant (Offline user session not found)\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718800)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
info: [LENS-SPACES-EXTENSION]: (from:resetSpaceSyncer) Clearing spaces/k8sClusters...
warn: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:25 InvalidGrant error, reset Lens state and set connected=false... invalid_grant (Offline user session not found) {"stack":"Error: invalid_grant (Offline user session not found)\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718800)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
info: [LENS-SPACES-EXTENSION]: (from:resetSpaceSyncer) Clearing spaces/k8sClusters...
info: [LENS-SPACES-EXTENSION]: (from:TokenRefresher) 9/1/2023, 10:52:27 forceRefresh() refreshing tokens...
error: [LENS-SPACES-EXTENSION]: 9/1/2023, 10:52:27 Error: Refresh token missing.
error: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:27 Unknown error .isAuthenticated() returns false {"stack":"Error: .isAuthenticated() returns false\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718025)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:27 Unknown error .isAuthenticated() returns false {"stack":"Error: .isAuthenticated() returns false\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718025)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:28 Unknown error .isAuthenticated() returns false {"stack":"Error: .isAuthenticated() returns false\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718025)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:28 Unknown error .isAuthenticated() returns false {"stack":"Error: .isAuthenticated() returns false\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718025)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:29 Unknown error .isAuthenticated() returns false {"stack":"Error: .isAuthenticated() returns false\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718025)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:31 Unknown error .isAuthenticated() returns false {"stack":"Error: .isAuthenticated() returns false\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718025)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:34 Unknown error .isAuthenticated() returns false {"stack":"Error: .isAuthenticated() returns false\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718025)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:34 Unknown error .isAuthenticated() returns false {"stack":"Error: .isAuthenticated() returns false\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718025)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:38 Unknown error .isAuthenticated() returns false {"stack":"Error: .isAuthenticated() returns false\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718025)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:38 Unknown error .isAuthenticated() returns false {"stack":"Error: .isAuthenticated() returns false\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718025)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:41 Unknown error .isAuthenticated() returns false {"stack":"Error: .isAuthenticated() returns false\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718025)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:52:54 Unknown error .isAuthenticated() returns false {"stack":"Error: .isAuthenticated() returns false\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718025)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:53:00 Unknown error .isAuthenticated() returns false {"stack":"Error: .isAuthenticated() returns false\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718025)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:53:03 Unknown error .isAuthenticated() returns false {"stack":"Error: .isAuthenticated() returns false\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718025)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 9/1/2023, 10:53:03 Unknown error .isAuthenticated() returns false {"stack":"Error: .isAuthenticated() returns false\n    at n.backOff.numOfAttempts [as request] (C:\\Users\\e001357\\AppData\\Roaming\\Lens\\node_modules\\lenscloud-lens-extension\\dist\\main.js:22:718025)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"}
`

**Comment by luandrea** [comment]
With version 6.2.5 I don't have this problem.

**Comment by ghostx3** [comment]
+ multiple hands
after connected, screen is just empty and require a manual refresh to appear.

**Comment by luandrea** [comment]
Thank you very much @ghostx3 your solution worked.

To refresh, just go to the menu in the top left corner, _View_ > _Reload_.
Or you can use the shortcut **Ctrl + R**

**Comment by ghostx3** [comment]
:) happy to help, but really wanted to draw attention that it is not normal. @MuhammedKalkan I'd appreciate if you could have a look, please.

**Comment by kopylash** [comment]
It is a duplicate of #111
