### ISSUE TITLE
Unable to view accessible namespace on cluster with limited permissions

### ISSUE THREAD

**Issue by kherock** [MuhammedKalkan/OpenLens#127]
Prior to OpenLens 6.3.0, I was able to view workloads and other resources on a namespace for a cluster where I do not have permission to list namespaces. However, since 6.3.0 onward (including latest 6.4.0-beta.13), I am unable to view anything. I am still able to navigate to resources by drilling down through links in the Helm Releases tab.

![image](https://user-images.githubusercontent.com/4993980/219236366-24390732-20a1-46ac-9e98-e7914b0c86ca.png)

**Comment by cfarrugia** [comment]
I have the same problem. We tried to see if the console generated any error. It did: We didn't have access to custom resources, and we fixed that. However, we still couldn't see cluster information. The console was silent and no errors there. Not sure if there is another way to pick up information from any other logs so we can help with this.

**Comment by kellen-miller** [comment]
This is a build repo, not the source repo. 

Open your issue here: https://github.com/lensapp/lens

**Comment by thiagoufg** [comment]
I have the same issue. By the ways, Lens shows the pods. OpenLens doesn't.

**Comment by johnny** [comment]
This is due to a breaking change in the Lens project, to move non core functionality into extensions: https://github.com/lensapp/lens/issues/6823 and https://github.com/lensapp/lens/issues/6983

Why pods and logs are considered optional? I've got no idea.

The fix is to install https://github.com/alebcay/openlens-node-pod-menu through the extensions.

**Comment by marafa-sugarcrm** [comment]
this repo is only to build the packages.
the source code (and github issues) are here: https://github.com/lensapp/lens

this can be closed

**Comment by jkroepke** [comment]
maybe its fixed in 6.4.3 https://github.com/lensapp/lens/pull/7279

But this, we cant solve that issue.
