### ISSUE TITLE
Not showing CPU and Disk metrics from Prometheus and Dashboard resources summary

### ISSUE THREAD

**Issue by trombini77** [MuhammedKalkan/OpenLens#129]
# Environment

- Windows 10 Enterprise
- OpenLens v6.4.0
- Kubernetes: AWS EKS v1.24
- Prometheus: v2.36.2

Print Screens from OpenLens v6.4.0:
![cluster-menu](https://user-images.githubusercontent.com/13336060/222612961-5404fd93-6329-4262-918f-c8a3c45915dc.jpg)

![nodes-menu](https://user-images.githubusercontent.com/13336060/222612914-d20b1760-423a-4a3a-b7b0-e384ce016e67.jpg)

![node-cpu](https://user-images.githubusercontent.com/13336060/222613005-ce20c353-50f6-4f48-a71d-5a0e5c0b5ad9.jpg)

![node-disk](https://user-images.githubusercontent.com/13336060/222613047-ab5c432b-3ffe-4823-a386-cdc48953f9f9.jpg)

As you can see, in the table of Nodes the metrics don´t appear but when you click on the node it is there in the right side modal for CPU, but for  DISK not.

And the Cluster resume also shows nothing except the Warning Events.

The last version of OpenLens that all of them works on is v6.2.5.

**Comment by littleccguy** [comment]
@trombini77 I have 6.4.2 on Windows 10 Ent as well. I have clusters in Azure on internal resources. Any cluster where I added the Lens Metrics stack are still working.  On new clusters, I no longer see the option under Cluster > Settings > Extensions > Lens Metrics.

Are you using the Prometheus from your AWS cluster or Lens Metrics? Just trying to understand if what I am seeing is related to yours, or if Lens Metrics has been removed from OpenLens

**Comment by jkroepke** [comment]
Whats your scrape interval of metrics in Prometheus?

**Comment by MuhammedKalkan** [comment]
Sorry but i dont have this issue.

**Comment by mnorrsken** [comment]
My experience is that it is always a problem with prometheus and/or kube-state-metrics configuration. Also you should take this issue to https://github.com/lensapp/lens as this repo only builds code from the base repo. I dont have this issue either and I'm running latest openlens and prometheus helm chart  v0.21.0 with prometheus v2.41.0

**Comment by MuhammedKalkan** [comment]
Closing since there is nothing related with build
