### ISSUE TITLE
Scroll bar gets stuck when opening two or more clusters simultaneously 

### ISSUE THREAD

**Issue by krishna2vinayak** [MuhammedKalkan/OpenLens#134]
I found with the latest 6.4.6 version, the scrolling bar gets stuck when two or more clusters are opened simultaneously. When I connect to the second cluster, the first cluster page will get the scrolling stuck. However, I can stroll by manual dragging the scroll bar. When I disconnect the second cluster page, the scroll gets back to normal.

**Comment by MuhammedKalkan** [comment]
You should open deveopment requests and bug reports to lens repo. Refer to readme
