### ISSUE TITLE
Error: SHA256 mismatch

### ISSUE THREAD

**Issue by borovoykirill** [MuhammedKalkan/OpenLens#141]
On macOS I have a problem when I'm trying to install OpenLens from scratch
`Error: SHA256 mismatch`

Removing the file and `brew update && brew upgrade` doesn't help.
Also when I'm trying to change SHA256 using `brew edit --cask openlens` I have an error `Error: Invalid usage: openlens doesn't exist on disk.`

How to install openlens in this case?
Thx in advance!

**Comment by cecobask** [comment]
Same issue here

**Comment by beinbm** [comment]
same here

**Comment by beinbm** [comment]
my workaround was to install the last version with:
`brew install --cask https://raw.githubusercontent.com/Homebrew/homebrew-cask/527a4805b5809dcdb28de1ce51265c428a848224/Casks/openlens.rb`

**Comment by borovoykirill** [comment]
> brew install --cask https://raw.githubusercontent.com/Homebrew/homebrew-cask/527a4805b5809dcdb28de1ce51265c428a848224/Casks/openlens.rb

works!! thx!
