### ISSUE TITLE
Error: The module was compiled against a different Node.js version 

### ISSUE THREAD

**Issue by wenbingzhang** [MuhammedKalkan/OpenLens#145]
version: v6.5.0
system: macos 12

Uncaught Exception:
Error: The module '/Applications/OpenLens.app/Contents/Resources/app.asar.unpacked/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 106. This version of Node.js requires
NODE_MODULE_VERSION 110. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
at Module.load (node:internal/modules/cjs/loader:1011:32)
at Module._load (node:internal/modules/cjs/loader:846:12)
at f._load (node:electron/js2c/asar_bundle:2:13330)
at Module.require (node:internal/modules/cjs/loader:1035:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (/Applications/OpenLens.app/Contents/Resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
at Module._compile (node:internal/modules/cjs/loader:1141:14)

**Comment by vitaliyf** [comment]
Similar, but perhaps for a different reason (I'm on M1 Mac, so arm64):

```
Uncaught Exception:
Error: dlopen(/Applications/OpenLens.app/Contents/Resources/app.asar.unpacked/node_modules/node-pty/build/Release/pty.node, 0x0001): tried: '/Applications/OpenLens.app/Contents/Resources/app.asar.unpacked/node_modules/node-pty/build/Release/pty.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/OpenLens.app/Contents/Resources/app.asar.unpacked/node_modules/node-pty/build/Release/pty.node' (no such file), '/Applications/OpenLens.app/Contents/Resources/app.asar.unpacked/node_modules/node-pty/build/Release/pty.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
at Module.load (node:internal/modules/cjs/loader:1011:32)
at Module._load (node:internal/modules/cjs/loader:846:12)
at f._load (node:electron/js2c/asar_bundle:2:13330)
at Module.require (node:internal/modules/cjs/loader:1035:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (/Applications/OpenLens.app/Contents/Resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
```

**Comment by thevops** [comment]
I have the same error after update

**Comment by andreosipov** [comment]
same erro

**Comment by mvillarjuan** [comment]
Same error after updating. 
Using MacOS 13.3.1(a) AMD64

**Comment by berezhinskiy** [comment]
M1 Ventura 13.4 (22F66)
```
λ uname -a
Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000 arm64
```
<img width="632" alt="Screenshot 2023-05-29 at 18 05 44" src="https://github.com/MuhammedKalkan/OpenLens/assets/502972/b651bd23-2c4b-4425-a95c-599277f6fd6a">

**Comment by lucagervasi** [comment]
Same issue here.

node -v
v18.16.0

lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 37 (Thirty Seven)
Release:	37
Codename:	ThirtySeven

**Comment by pshakhov** [comment]
Same error after upgrading to version v6.5.0
Using MacOS 13.4 i9

**Comment by krokofant** [comment]
Might be related to the 6.5 version. Seems similar to this issue that's been active since 6.5 alpha started.

See lensapp/lens issue 7523

**Comment by mcouthon** [comment]
Anyone knows of a workaround to downgrade in the meanwhile?

**Comment by cardalda** [comment]
> ~Anyone knows of a workaround to downgrade in the meanwhile?~
> 
> Right, just download the previous version ([6.4.15](https://github.com/MuhammedKalkan/OpenLens/releases/tag/v6.4.15)) from the releases page, and install it.

How can I prevent it from being upgraded again? I didn't do anything to get this broken version...

**Comment by air3ijai** [comment]
> How can I prevent it from being upgraded again? I didn't do anything to get this broken version...
 
#96 --> https://github.com/MuhammedKalkan/OpenLens/issues/81#issuecomment-1369754947

**Comment by MuhammedKalkan** [comment]
Turned off auto update for 6.5.0 for mac and linux

No errors in build process so far, that means no clue to solve as of now.

**Comment by waldner** [comment]
Same here with 6.5.0

**Comment by niorg** [comment]
Same problem with the newly released 6.5.1

**Comment by jkroepke** [comment]
#147 may fix this issues.

Everyone can help to validate this by checkout the pre-builds artefacts from https://github.com/MuhammedKalkan/OpenLens/actions/runs/5115183592. arm64 users are welcome to validate cross-arch builds.

**Comment by cardalda** [comment]
I did 
brew upgrade openlens
on macos

![image](https://github.com/MuhammedKalkan/OpenLens/assets/2777067/8c4673d7-73c8-4912-bc49-a7451efc3082)

removing the .dmg before the next attempt gave exact results...

**Comment by thevops** [comment]
The same for me. As a workaround try to uninstall OpenLens, download dmg package from Github, and install it manually. For me, it worked.

**Comment by MuhammedKalkan** [comment]
Guys maybe i should put a warning on Readme. SHA mismatch is caused by rebuild and it should be fixed at whatever repo is hosting install scripts. They keep old SHA and new rebuilds are not updated accordingly

1- Either install manually
2- Or fix that  SHA at host

**Comment by jkroepke** [comment]
> should be fixed at whatever repo is hosting install scripts. 

https://github.com/Homebrew/homebrew-cask/blob/3e3a2f6b124bf3c8d19a4b3f282e8549c30c5c13/Casks/openlens.rb#L5-L6

they may not change there.

**Comment by MuhammedKalkan** [comment]
Just pointing out that can not be resolved here. If there is an option to skip SHA check, they can use that aswell

**Comment by MuhammedKalkan** [comment]
I would suggest to use 6 digit short commit sha. We can append that to binaries. Like   OpenLens-6.5.1-arm64-mac-**2ef129c**.zip

**Comment by jkroepke** [comment]
commit hash would be a bad one, since you can no identify by version number, which is newer. Job ID always count up.

> Does homebrew trace builds by their tags ?

As I know, there is no automatic version bump. its more like `brew bump-cask-pr --version 5.6.0 openlens`

**Comment by MuhammedKalkan** [comment]
Right , what you suggest is to add job it to release tags ? Like 5.6.0.-120 ?

**Comment by jkroepke** [comment]
Looking to semver, we should mark the as `5.6.0+${{ github.run_id }}`. Numbers after `+` considered as build metadata.

Yes, then we have an always incrementing build number. The Windows and [Chrome Version](https://www.chromium.org/developers/version-numbers/) number has this, too. This is fine from my point of view and would result more transparency.

**Comment by MuhammedKalkan** [comment]
Alright , that makes sense  if this will be a remedy for SHA mess

**Comment by MuhammedKalkan** [comment]
Agreed.

**Comment by biswanaths** [comment]
This works for me 
```
cd /Applications/OpenLens.app/Contents/Resources/app.asar.unpacked/
rm -rf node_modules/node-pty/
npm install 
```
