### ISSUE TITLE
Cannot connect to docker-desktop cluster in MacOS

### ISSUE THREAD

**Issue by roberto-microsoft** [MuhammedKalkan/OpenLens#151]
Shows error: **Failed to start connection: ValidationError: "clusters[0].cluster.server" is not allowed to be empty**

**Comment by MuhammedKalkan** [comment]
This looks like that it belongs to lens repo. Have you tried this with lens version?

**Comment by roberto-microsoft** [comment]
No I haven't, just using the open version.
Thing is this issue appeared recently after 2 or 3 latest updates, I removed my docker-desktop configuration and re-created it and the issue persist, it's not an issue with the Cloud clusters, just the local one.

**Comment by MuhammedKalkan** [comment]
Please try with Lens version and reopen if its only issue in  OpenLens builds.

Because no source code is altered here
