### ISSUE TITLE
为什么其中一个dp的没了监控，提示Metrics not available at the moment

### ISSUE THREAD

**Issue by wsw136** [MuhammedKalkan/OpenLens#152]
![image](https://github.com/MuhammedKalkan/OpenLens/assets/36026057/1c2eeca3-78a6-4cf9-86ac-c6c9b0740594)

![image](https://github.com/MuhammedKalkan/OpenLens/assets/36026057/fa601d33-f7b3-4d6a-a771-c5b89726a445)

**Comment by MuhammedKalkan** [comment]
I dont think this is a bug
