### ISSUE TITLE
Delete pod and the lens does not react

### ISSUE THREAD

**Issue by 873307947** [MuhammedKalkan/OpenLens#154]
On the pod page, click Delete pod and the lens does not react
![image](https://github.com/MuhammedKalkan/OpenLens/assets/23731971/009e5c77-9355-48f0-be90-69f2c32bd4bc)
![image](https://github.com/MuhammedKalkan/OpenLens/assets/23731971/f093dc5b-667f-4539-b10f-3bdca4dfe2ee)

**Comment by MuhammedKalkan** [comment]
Have you checked it from CLI that the pod is actually removed ?

Problem probably is in cluster

**Comment by 873307947** [comment]
use kubectl delete pod to success, use delete not work for pod page

**Comment by MuhammedKalkan** [comment]
Two more suggestions

1- Try with Lens if they have the same error and open error there
2- If not, try at @alebcay who is the owner of the extension

We are not changing source code and cant resolve issues unless it is proven to be a build issue

**Comment by HL230606** [comment]
ok, tks

**Comment by HL230606** [comment]
is lens bug https://github.com/lensapp/lens/issues/7835

**Comment by diegocejas** [comment]
I have the same issue, I'm able to delete any pod from the command line with kubectl but not from Lens.
This is clearly a problem with this app, please fix.

**Comment by danilogco** [comment]
Well, the PR was closed. But it still happening. Does anyone know a workaroud for it?
