### ISSUE TITLE
Auto Updater Broken

### ISSUE THREAD

**Issue by MuhammedKalkan** [MuhammedKalkan/OpenLens#155]
We need *.yml files in the latest tag for auto updater to work. Also inside that files we need to check if our new build numbered releases are referenced. IF not auto updater will not work all the same  @jkroepke

**Comment by MuhammedKalkan** [comment]
Also same windows setup files added twice to releases. OpenLens.... and OpenLens.Setup....  
We need to make sure only one which is referenced from YML files exist there

**Comment by jkroepke** [comment]
The OpenLens.exe file is a portable version of OpenLens (without Setup) while the Setup one is the classical setup.exe

**Comment by MuhammedKalkan** [comment]
Great then, we can ignore that

**Comment by jkroepke** [comment]
maybe #156 helps here to fix the issue. On a local build, the lastest files are visible again.

**Comment by MuhammedKalkan** [comment]
Ok. Lets check contents as well and make sure they are pointing to the right file names

**Comment by MuhammedKalkan** [comment]
Still no yml files in the latest tag. Wierd

**Comment by jkroepke** [comment]
latest is back again, however from semver point of view, 6.5.2 is higher than 6.5.2-309.

But that should fixed on next version of Lens
