### ISSUE TITLE
Lens metrics missing

### ISSUE THREAD

**Issue by micgruber** [MuhammedKalkan/OpenLens#165]
What I miss in the current version are the kubernetes lens metrics: 6.5.2-356. Is it also possible to get it for open lens?

![image](https://github.com/MuhammedKalkan/OpenLens/assets/19686895/123ec530-acf9-4236-a0dc-380b201b2b83)

**Comment by jkroepke** [comment]
Hi @micgruber,

Mirantis does not offer the sources for the extensions.
