### ISSUE TITLE
AWS EKS 1.27 is not wokring with latest openlens.

### ISSUE THREAD

**Issue by ashiq-betaflux** [MuhammedKalkan/OpenLens#166]
I am facing an issue where OpenLens (version 6.5.2-366) fails to connect to my AWS EKS cluster (Kubernetes version 1.27). I receive the following error message: "Failed to get /version for clusterId=c6248b608f4a8e196b57022db79ad64f: Unauthorized."

I have confirmed that my kubeconfig file and credentials are correct. However, OpenLens is unable to retrieve the cluster information.

I kindly request your assistance in resolving this compatibility issue or providing guidance on how to resolve it.

Thank you for your attention to this matter.

**Comment by lisenet** [comment]
I'm not sure if you've seen this, but:

"This repo ONLY PROVIDES SIGNED BINARIES AND DOES NOT ALTER SOURCE CODE for the [OpenLens repo](https://github.com/lensapp/lens/issues). For software issues regarding OpenLens or the Lens IDE, go to the Lens repo and open an issue there."

**Comment by MuhammedKalkan** [comment]
Please file an issue in source repo
