### ISSUE TITLE
Support of appimage update

### ISSUE THREAD

**Issue by FStefanni** [MuhammedKalkan/OpenLens#168]
Hi,

it could be nice to support the update mechanism provided by AppImage. Here the official documentation:

<https://github.com/AppImage/AppImageSpec/blob/master/draft.md#update-information>

Basically, it suffice to generate a zsync file and upload it into the releases.
Regards

**Comment by jkroepke** [comment]
Hi @FStefanni,

it's not in our control. The Auto-Updater comes from the underlaying framework [electron](https://www.electron.build/auto-update) and we don't have the capacity to maintain out-of-tree update path for multiple target.

**Comment by FStefanni** [comment]
Hi,

sorry, maybe I have been not clear.
The mechanism I am referring to is not related to electron and it is not an auto-update mechanism.
It is a mechanism implementable by any App Image, just by providing an extra file (`zsync`).
Having such a file, App Images can be upgraded by using some tools, in a similar way as other normally installed apps.
And it is not an out-of-tree, it is a file dynamically generated, which can be generated during the App Image package generation.

Regards
