### ISSUE TITLE
Logs Menu on pods Linux

### ISSUE THREAD

**Issue by juliocesarsantos1020** [MuhammedKalkan/OpenLens#169]
Hello,

is it normal that we no longer have the records in the latest version of openlens even using @alebcay/openlens-node-pod-menu?
I'm using Ubuntu 22.04.3 LTS
![Captura de tela de 2023-08-23 23-16-04](https://github.com/MuhammedKalkan/OpenLens/assets/28718762/fd507545-9b8c-4dde-91b9-a6fad7035dc0)

**Comment by uday1kiran** [comment]
When I installed latest version, the logs option is missing.

So, I installed extension:  @alebcay/openlens-node-pod-menu
But after that, lens is crashing.

Installed older version: OpenLens.6.5.2-356
It is working.

**Comment by elovin** [comment]
Hm I think you should create an issue in the extension repository then.
https://github.com/alebcay/openlens-node-pod-menu
