### ISSUE TITLE
'openlens' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by mikhatanu** [MuhammedKalkan/OpenLens#171]
Hello, I tried installing openlens from chocolatey. After installing, it opens openlens automatically. After closing it,  I tried to run openlens in cmd to open it again, but it returns an error:

![image](https://github.com/MuhammedKalkan/OpenLens/assets/8099814/c2a062c0-9ea7-480f-a8c2-14d0fc9dc3d0)

Is there any guide on how to launch openlens when installing with chocolatey?

**Comment by MuhammedKalkan** [comment]
Add lens to env var path if not already added and try closing that terminal and reopen a new one.

**Comment by moni-dips** [comment]
I just installed this with chocolatey, and it started and worked fine during install, but I have no idea how to launch openlens again without reinstalling. It does not seem like openlens added anything to Path either on system or my user when it was installed.
It would have been nice if openlens added itself to the start menu, where I usually start gui apps from.
