### ISSUE TITLE
update-desktop-database: command not found

### ISSUE THREAD

**Issue by rgaiacs** [MuhammedKalkan/OpenLens#175]
`sudo dpkg -i OpenLens-6.5.2-366.amd64.deb` shows

```
/var/lib/dpkg/info/open-lens.postinst: line 10: update-desktop-database: command not found
```

**Comment by redtux** [comment]
> update-desktop-database: command not found

This seems to be a simple dependency issue. The utilities for .desktop files are missing on your system.

@rgaiacs, you can manually install the required package like this:

```
sudo apt install desktop-file-utils
```

**Comment by rgaiacs** [comment]
Thanks!
