### ISSUE TITLE
Missing features in OpenLens Build

### ISSUE THREAD

**Issue by phpwutz** [MuhammedKalkan/OpenLens#179]
Hi, I noticed 2 things that work in Lens, but they are just missing  in OpenLens right now (i have the latest version 6.5) :

1: pods do not show memory usage in the "pods" table
2: "open terminal" and "open logs" buttons are missing from the "pod" sidebar

both these things work in the regular Lens distribution, and I cannot see how they are related to the "cloud" extension.

any ideas how to fix this?

best regards

**Comment by davistran86** [comment]
@phpwutz please read the README, you can install them by using extensions

**Comment by sossaman** [comment]
Hello,
extensions seem to not work in openlens 6.5.2-366 on Ubuntu 22.04.
I tried installing them both using the link and loading the tarball directly, restarting the application every time.
I also reinstalled the application several time removing also the folder in /home/user/.config/

**Comment by sossaman** [comment]
Update.
I solved the problem by deleting the folder  /home/user/.k8slens

**Comment by cbjjensen** [comment]
@sossaman ty , that also resolved my issue!
