### ISSUE TITLE
Latest release fails to start on M1 MacBook Air

### ISSUE THREAD

**Issue by holograph** [MuhammedKalkan/OpenLens#18]
The 6.0.0 release downloads successfully but fails to start (I tried both replacing and clean reinstall, as well as re-downloading. Same result):

<img width="372" alt="image" src="https://user-images.githubusercontent.com/1114848/182045428-1f2fd373-a7c2-4ff7-9378-9ce900ee1456.png">

I'm not sure how to even start debugging this, but will be happy to help...

**Comment by MuhammedKalkan** [comment]
Which version have you tried ?

**Comment by holograph** [comment]
6.0.0, as mentioned, with the -arm64.dmg binary. I just tried the Intel binary and it's working fine, albeit relatively slowly.

**Comment by MuhammedKalkan** [comment]
@jkroepke may want to take a loom

**Comment by jkroepke** [comment]
This is expectable. On ARM builds require a code signature.

> New in macOS 11 on Macs with Apple silicon, and starting in macOS Big Sur 11 beta 6, the operating system enforces that any executable must be signed before it’s allowed to run.  

> This new policy doesn’t apply to translated x86 binaries running under Rosetta 2, nor does it apply to macOS 11 running on Intel-based platforms.

- https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-universal-apps-release-notes

 Looking forward for #1 here.

**Comment by holograph** [comment]
Interesting that it says "damaged" and not "unsafe" or "unsigned". Is there a known local workaround?

**Comment by MuhammedKalkan** [comment]
Here is the workaround  https://github.com/MuhammedKalkan/OpenLens/issues/18#issuecomment-1200501408

**Comment by b-a-t** [comment]
> Here is the workaround [#18 (comment)](https://github.com/MuhammedKalkan/OpenLens/issues/18#issuecomment-1200501408)

Yep, that worked for me! Maybe, if necessary, we can create crowdfunding for the developer certificate to sign binaries?

**Comment by MuhammedKalkan** [comment]
> > Here is the workaround [#18 (comment)](https://github.com/MuhammedKalkan/OpenLens/issues/18#issuecomment-1200501408)
> 
> Yep, that worked for me! Maybe, if necessary, we can create crowdfunding for the developer certificate to sign binaries?

That was what i ve been thinking recently. Maybe a patreon account would help. Open to alternatives if community supports it

**Comment by jkroepke** [comment]
I will also ask a cool guy if he want to give access to sign the App here.

**Comment by jkroepke** [comment]
> Interesting that it says "damaged" and not "unsafe" or "unsigned". Is there a known local workaround?

Open Console.app (System Log Viewer) on Mac and start to stream Logs and open OpenLens.app, than you will see an Apple Policy Violation error.

**Comment by jvanzyl** [comment]
I'd be happy to sponsor the project if sponsorship is enabled for the project.

**Comment by rpardini** [comment]
Again, interesting this. on Mac Intel amd64 12.5, I get a clear indication of the lack of signature; wonder why a different error on arm64 only?
![image](https://user-images.githubusercontent.com/639959/183258152-888f52c8-6f25-4302-af0d-7e48f29004fc.png)
on `amd64` 12.5 👆

**Comment by jkroepke** [comment]
> wonder why a different error on arm64 only?

Apple decide that the signature policy affects only native arm64 builds
