### ISSUE TITLE
Does Lens close its source code?

### ISSUE THREAD

**Issue by dictcp** [MuhammedKalkan/OpenLens#183]
Hi all,

I am aware this repos [OpenLens](https://github.com/MuhammedKalkan/OpenLens) only builds source code from https://github.com/lensapp/lens. 

But I am also aware recent Lens release (eg. https://forums.k8slens.dev/t/lens-2023-09-19-the-one-with-the-applications-view/1409) including bugfix and new feature (feature release in Sept 2023 and patch release in Dec 2023). However, the upstream repos https://github.com/lensapp/lens with release in May 2023 and last commit in Aug 2023. I think it is reasonable to believe the [Mirantis, Inc.](https://mirantis.com/) plan to build its advantage by not release its latest source code. While it is normal for a business to earn money, as community member, we may need to think how to make its OpenLens working, say by forking it and maintain it by the community.

**Comment by dictcp** [comment]
related discussion in upstream repo
https://github.com/lensapp/lens/discussions/7885#discussioncomment-7130895
https://github.com/lensapp/lens/issues/7936

**Comment by petrkr** [comment]
> related discussion in upstream repo https://github.com/lensapp/lens/discussions/7885#discussioncomment-7130895 [lensapp/lens#7936](https://github.com/lensapp/lens/issues/7936)

404 not found
