### ISSUE TITLE
OpenLens Menus incomplete (Workloads / Storage / Config) on 6.5.2.366

### ISSUE THREAD

**Issue by StephaneDci** [MuhammedKalkan/OpenLens#185]
OpenLens 6-5-2-366 on Linux Mint.

When I connect on a K8s cluster I only get a partial load on some menus ( missing the expending arrows): 

![image](https://github.com/MuhammedKalkan/OpenLens/assets/45298514/ad268bf7-70fb-451a-896a-4fd55494558f)

Helm > Release is the only place where I retrieve infos on my Namespace.

Also I tried on 6.5.1, same bug.

No errors displays on dev tools.

**Comment by mossroy** [comment]
This happened to me some time ago, when there was something broken in my target cluster.
Like a component down or mis-behaving (DNS for example, I don' remember exactly).
Try to investigate with kubectl commands, start by having a look at the events of the cluster
