### ISSUE TITLE
Namespaces delete button has no confirmation dialog

### ISSUE THREAD

**Issue by d-jsb** [MuhammedKalkan/OpenLens#190]
First of all thanks for this great tool! :)
Version: 6.5.2-366
Issue: The delete button of the namespace info pannel is unprotected, e.g. no confirmation dialog is shown. 
Steps to reproduce:
Create a test namespace that can be deleted
Go to the namespaces view
Select the test namespace
On the info panel of the namespace click on the trashcan icon 
The namespace including everything in it gets delete at once without further warning / confirmation.

This is really dangerous, a confirmation dialog (which is in place for other delete operations) would be highly appreciated.

**Comment by absmith82** [comment]
This is not the repository where the app is developed.  the app has now been close sourced and is not in active development anymore.  There is a very small portion of the community that would like to fork an opensource this again, however I don't know that there are many developers that are interested in doing this at this point in time.
