### ISSUE TITLE
Make 'no updates' notice more visible

### ISSUE THREAD

**Issue by lukasz-mitka** [MuhammedKalkan/OpenLens#192]
I missed the `Lens Closed its source code. So please do not expect any more updates.` notice at first.
Please make it prominent.

**Comment by fbaldo31** [comment]
A new fork is close to deliver a new version so future versions could be built in fact @MuhammedKalkan what do you think about publishing binaries from our repo [here](https://github.com/Open-Lens/app) ?
As you have the experience of the release process your advice would be appreciated on this [PR](https://github.com/Open-Lens/app/pull/9) 

Thanks

**Comment by busches** [comment]
That "fork" lost all previous git history and just renamed everything.
