### ISSUE TITLE
Support for grafana agent/alloy

### ISSUE THREAD

**Issue by descof** [MuhammedKalkan/OpenLens#196]
Hi,
Is it possible to retrieve metrics in open lens when deploying grafana agent/alloy? I had no problems with the kube prom stack but now i want to use grafana alloy and I cannot see my metrics.
I tried to specify the grafana alloy service in open lens setting but I still get the message: metrics not available.
Does anyone try to get metric in open lens with grafana agent/alloy ?

**Comment by jkroepke** [comment]
> Is it possible to retrieve metrics in open lens when deploying grafana agent/alloy?

No
