### ISSUE TITLE
OpenLens not sync'ed with latest upstream Lens release (v2024.1.300751-latest)

### ISSUE THREAD

**Issue by Trikenstein** [MuhammedKalkan/OpenLens#199]
As of 2024-05-20, the upstream latest version is [v2024.1.300751-latest](https://github.com/lensapp/lens/releases/tag/v2024.1.300751-latest). Is it OK to sync OpenLens build binary accordingly?

EDIT: oh saw in [commit history](https://github.com/MuhammedKalkan/OpenLens/commits/main/) you did cancel the build. In particular the note added on 2024-05-03:

> Lens Closed its source code. So please do not expect any more updates.

What is the ultimate reason that you can no longer build installable binary from source?

1. Because of legal issue with https://github.com/lensapp/lens ?
2. Because of technical issues so that source code from  https://github.com/lensapp/lens is no longer sufficient to produce a working app?

Ultimately, can I build myself a Linux binary from source? Are the [Github actions](https://github.com/MuhammedKalkan/OpenLens/tree/main/github/workflows) from your repo  still valid ?

**Comment by kevinpetit** [comment]
The lensapp/lens repository only contains a few text files and images - it no longer contains the source code for Lens.
So it's impossible to build a new release from it.
