### ISSUE TITLE
Add a HomeBrew formula

### ISSUE THREAD

**Issue by janhoy** [MuhammedKalkan/OpenLens#2]
It would be nice to be able to install openlens as a Cask using `brew install openlens` on macOS.

So I made a formula at https://github.com/janhoy/homebrew-cask/blob/open-lens/Casks/openlens.rb which works locally. I assume that the `.dmg` here is UniversalBinary, i.e. will work on both x64 and arm64? I have only tested on arm (M1).

However there are two issues that must be solved for us to submit a PR for it:

1. The Mac app is not signed, which is a blocker for new users. See #1 
2. This repository needs 30 forks, 30 watchers and 75 stars to be eligible for HomeBrew:

       audit for openlens: failed
        - GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
       Error: 1 problem in 1 cask detected

**Comment by carlocab** [comment]
Just a few notes:

What you created is actually a cask (installs a pre-built artefact, only works on macOS) rather than a formula (typically built from source, can work on both macOS and Linux).

As for the notability requirement, you can always host your cask in your own tap (a Git repo that contains casks/formulae).

Here are some docs to help you get started:

https://docs.brew.sh/Taps
https://docs.brew.sh/Interesting-Taps-and-Forks
https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/

**Comment by janhoy** [comment]
A new tap for just one app sounds overkill, if it requires two commands by the end user (add tap, then install)? Are there any obvious benefit with defining a new tap?

Since we need a signed Mac App, I think a Cask is the right way to go, as it will pull the pre-built (and signed) DMG file from our release repo.

My note above about Universal Binary is false though, so it is x86. As soon as GitHub Actions can build arm, then we can add the arm64 variant.

**Comment by carlocab** [comment]
> A new tap for just one app sounds overkill, if it requires two commands by the end user (add tap, then install)?

You can install from taps hosted on GitHub in a single command, as long as the repo name starts with `homebrew-`. For example, I have a GitHub repo called `homebrew-personal`, and anyone can install formulae from it using
```sh
brew install carlocab/personal/foo
```

> Are there any obvious benefit with defining a new tap?

You get more control over your cask, which some developers prefer. This also means you don't need to meet any of the requirements for inclusion into a Homebrew-owned repository.

**Comment by janhoy** [comment]
Got it. Also according to https://docs.brew.sh/Acceptable-Casks this will be an "Unofficial" binray, which will not be approved as a main cas anyway:

>An allegedly unmodified compiled binary, by a third-party, of a binary that has no existing build by the owner of the source code.

Thus the tap route is probably the way to go, as it is unlikely that we'll be able to persuade Mirantis to publish official binaries for the open source version, even if we submit a PR for it :(

**Comment by carlocab** [comment]
A formula that builds from source can likely be made acceptable for inclusion in `homebrew-core`. Just FYI. But you can, of course, choose to host your own cask instead of or in addition to a formula.

**Comment by janhoy** [comment]
Can you make a formula sign the Mac binaries? Where would you place the signing certificate?

**Comment by alebcay** [comment]
I don't think there's any precedent of a Homebrew formula signing Mac binaries. You could have the formula download a signing certificate as a resource and use it to sign the binary, but I see no benefit to this approach compared to just distributing a binary that is already signed.

Homebrew does perform "on-the-fly" signing of CLI applications (distributed as formulae) but my understanding is that this ad-hoc signing works differently for apps.

In any case, I think cask is probably the path of choice here. Formulae are usually CLI apps (can't install outside of the Homebrew prefix, so can't install e.g. to `/Applications`). Neither provides a solution to the issue of the app being untrusted/unsigned.

**Comment by Anticom** [comment]
@janhoy What about https://github.com/ykursadkaya/homebrew-openlens? I've been using it right after openlens came to live. Does your formula add any other improvements over ykursadkaya's one?

**Comment by janhoy** [comment]
> @janhoy What about https://github.com/ykursadkaya/homebrew-openlens? I've been using it right after openlens came to live. Does your formula add any other improvements over ykursadkaya's one?

Have you tried it? Do they build and sign their own binaries or use the one from this repo?

**Comment by Anticom** [comment]
> > @janhoy What about https://github.com/ykursadkaya/homebrew-openlens? I've been using it right after openlens came to live. Does your formula add any other improvements over ykursadkaya's one?
> 
> Have you tried it? Do they build and sign their own binaries or use the one from this repo?

I'm using it ever since it was created without any issues. The artifacts aren't signed tho, that's a good point!
For me personally that was never a big issue since I've just allowed the execution.

**Comment by MuhammedKalkan** [comment]
Is this still a thing ? Homebrew produces unsigned packages. 
And seems this will not be added to mainstream tap, so what is the situation here ?

**Comment by jkroepke** [comment]
I provided one homebrew Cask here:

https://github.com/jkroepke/homebrew-openlens

```
brew install jkroepke/openlens/openlens
```

> Homebrew produces unsigned packages.

This is not true. Local builds are always signed with an ad-hoc signature. Cask (with will use pre-build binaries from this repository), are not touched by brew. But this is not a problem, since the pre-build binaries are already signed.

**Comment by jkroepke** [comment]
@MuhammedKalkan If you want, you can link it in the README.md and close this issue. Since homebrew TAP must be beginn with `homebrew-`, we are not able to merge the homebrew file into this repository. A Long term solution would be a dedicated GitHub Organization (e.g. openlens-redistribution) where we can put both repositories into it.

**Comment by bevrist** [comment]
I only found this issue after creating [this PR](https://github.com/Homebrew/homebrew-cask/pull/135007) for `homebrew-cask`, but the homebred-cask maintainers did accept this project as is. 
anyone can now install the openlens binaries from this repo via `brew install --cask openlens`
