### ISSUE TITLE
Error: ERR_FAILED (-2) loading 'http://localhost:64661'

### ISSUE THREAD

**Issue by jiangxiaoqiang** [MuhammedKalkan/OpenLens#23]
when I open the openlens 6.0.0 in macOS 12.5 with M1 pro chip,shows error:

`Error: ERR_FAILED (-2) loading 'http://localhost:64661'`

what should I do to fix this problem?

<img width="256" alt="image" src="https://user-images.githubusercontent.com/4521375/182655274-7e6eee82-f759-47a4-9bfb-6e222ad3825d.png">

**Comment by MuhammedKalkan** [comment]
İs there an active process that prevents certain ports? Maybe a corporate antivirus or firewall of some kind. At first glance,it  doesnt look like something with Lens

**Comment by jvanzyl** [comment]
I believe port 64661 is Apple Xsan. Are you using a form of remoting into a Mac and trying to run Lens? If so you may need to use the general security fix which is:

`sudo xattr -r -d com.apple.quarantine "/Applications/OpenLens.app`

**Comment by jiangxiaoqiang** [comment]
Finally I found that my kubernetes cluster certificate was expired, the default valid time was 1 year when using kubeadm to install the kubernetes cluster.
