### ISSUE TITLE
KDE desktop menu entry doesn't work

### ISSUE THREAD

**Issue by toralf** [MuhammedKalkan/OpenLens#24]
I do have tried this under a hardend stable Gentoo Linux:
```
$ cat ~/.local/share/applications/openlens.desktop 
[Desktop Entry]
Name=OpenLens
Exec=/usr/local/bin/OpenLens-6.0.0.AppImage %U
Terminal=false
Type=Application
Icon=lens
StartupWMClass=Lens
Comment=OpenLens
MimeType=x-scheme-handler/lens;
Categories=Development;
```

It worked fine with Lens in the past.
With OpenLens the start up window does not appear. After I removed the %U the app startup window at least appeared - and then KDE hangs.
Starting from the command line works flawlessly.

**Comment by MuhammedKalkan** [comment]
Have you tried with Lens 6.0.0 ? This repo only builds and does not alter source code. It is possible that 6.0.0 build has a bug

**Comment by toralf** [comment]
> Have you tried with Lens 6.0.0 ? This repo only builds and does not alter source code. It is possible that 6.0.0 build has a bug

Yes, tried it 2 hours ago with that latest version.

**Comment by MuhammedKalkan** [comment]
Dont have KDE installed, need more debug info to come up with a solution

**Comment by toralf** [comment]
seems to be solved here after kde-plasma update - so thx
