### ISSUE TITLE
MacOS arm64 version seems to be broken and unusable

### ISSUE THREAD

**Issue by jozefKruszynski** [MuhammedKalkan/OpenLens#26]
I tried downloading the arm64.dmg and the arm64.zip of the new version 6.0.0 release, however in both cases after several downloads and re-downloads the resulting application cannot be opened.

Mac OS version: Ventura Version 13.0 Beta (22A5311f)
Hardware: MacBook Pro Apple M1 Pro

Screenshot of error message:
![Screenshot 2022-08-05 at 09 02 31](https://user-images.githubusercontent.com/60214390/183021341-ff27c9d8-e414-4f0a-866c-936b6114ff8e.png)

Crash report:

[openlens-crash-report.txt](https://github.com/MuhammedKalkan/OpenLens/files/9266249/openlens-crash-report.txt)

**Comment by MuhammedKalkan** [comment]
Did you take a look at #18

**Comment by jozefKruszynski** [comment]
My apologies, for not searching properly in resolved issues, I guess I'm too stupid this morning to think of these things.

Thanks for the superfast response.

And thanks for your work in this project.
