### ISSUE TITLE
add mac arm64 (m1) build

### ISSUE THREAD

**Issue by b2un0** [MuhammedKalkan/OpenLens#3]
^ add mac arm64 (m1) build

the amd64 version is very very slow on m1 mac

**Comment by MuhammedKalkan** [comment]
Github actions currently don't support M1 build. No virtual env has been released yet

See: [Issue](https://github.com/actions/virtual-environments/issues/2187)

**Comment by justdan96** [comment]
You can use Mac Stadium to create M1 and Intel builds: https://www.macstadium.com/opensource

**Comment by jpuskar** [comment]
Just wanted to report that OpenLens 5.4.4 is pretty slow on my M1.

**Comment by NotANormalNerd** [comment]
You can cross build a universal binary on any mac. 

`"build:mac": "yarn run compile && electron-builder --mac --universal --dir",` would do the trick.
