### ISSUE TITLE
error 'Found incompatible module'

### ISSUE THREAD

**Issue by neeltom92** [MuhammedKalkan/OpenLens#35]
seems it works only if the node version is ">=16 <17"
I had to downgrade the version to install it
![image](https://user-images.githubusercontent.com/26869835/188285259-f9d00cba-ff2e-40f7-904b-637d58e2af47.png)

**Comment by MuhammedKalkan** [comment]
What is the purpose of this issue again ?

**Comment by neeltom92** [comment]
its failing at installation , was checking this doc : https://blog.devgenius.io/is-it-time-to-migrate-from-lens-to-openlens-75496e5758d8

while running this command its throwing the error
===
Build macOS Apple Silicon and Intel binaries: env ELECTRON_BUILDER_EXTRA_ARGS="--arm64 --x64 --config.dmg.sign=false" make build
===
