### ISSUE TITLE
Add test strategy for workflows

### ISSUE THREAD

**Issue by jkroepke** [MuhammedKalkan/OpenLens#39]
Currently, it's not possible to verify the workflow which build lens runs successfully before merge into main.

This results into required reverts in the history, atleast by me.

A proposal would be to enable OpenLens builds on pull requests but exclude the push step on them.

**Comment by MuhammedKalkan** [comment]
So when a pull request is made, will artifacts produced  be attached to that pull request ?

**Comment by jkroepke** [comment]
uploaded artifacts can be stored inside the workflow. No need for attach them manual

https://github.com/adorsys/keycloak-config-cli/actions/runs/3055350274 (scroll to bottom)

**Comment by MuhammedKalkan** [comment]
Attached link is using actions/upload-artifact@v3. 
Push workflow needs to be modified as to skip creating releases and produce artifacts using that action. 
if github actions allow us to run a job only on pull requests but skip on merge, this can be done i guess
