### ISSUE TITLE
Windows Defender blocks unsigned packages. 

### ISSUE THREAD

**Issue by nadeda01** [MuhammedKalkan/OpenLens#4]
As the package is unsigned, Windows Defender blocks package from installation.

**Comment by glloyd2010f** [comment]
As a work around you can unblock the exe, assuming you have admin rights. But I agree this should be fixed.

**Comment by BlackCetha** [comment]
Sometimes it doesn't even show the dialog box for unblocking. A workaround seems to be launching the exe from the old CMD.

**Comment by toralf** [comment]
> Sometimes it doesn't even show the dialog box for unblocking. A workaround seems to be launching the exe from the old CMD.

Works - thx!

Windows is such a painful thing ...

**Comment by sanarena** [comment]
We have 5 patterns now.  Getting closer for a signed windows binary?

**Comment by MuhammedKalkan** [comment]
You can see amount collected at the patreon page. Currently 34.75$. So not yet

**Comment by jkroepke** [comment]
Does someone test if a self-signed code signature would resolve the issue?

**Comment by nadeda01** [comment]
Just using work arounds - we can close this issue.

**Comment by jkroepke** [comment]
Maybe explain your work arounds?

**Comment by MuhammedKalkan** [comment]
We have  about 98.7$ (a few bucks lower maybe when transaction fees apply)  ready for a windows sing cert. Do you have any recommendations for a purchase ?  I am thinking about comodo : [85$ for one year](https://comodosslstore.com/codesigning.aspx) 
@sanarena @jkroepke @janhoy

**Comment by sanarena** [comment]
I do not have much experience in code signing. [I found this one a bit cheaper.](https://www.ssl2buy.com/comodo-code-signing-certificate.php)

**Comment by MuhammedKalkan** [comment]
I tried to purchase from comodo but sectigi which issues certs demanded id with the address written on it. Unfortunately we dont have that kind of id and they rejected my documents. Talked  them twice on the phone and decided to get a refund. Still waiting for that, i am afraid that there might be a possibility that they may not refund it. Such a headache for just a cert

**Comment by JeremyTheocharis** [comment]
@MuhammedKalkan If this is still open, you can contact us. We could sign LTE versions of OpenLens for you and it would be great to have a cool "Sponsored by United Manufacturing Hub" banner somewhere. If you are interested, feel free to contact us: 

https://www.umh.app/

Ask in your message for jeremy :)

**Comment by MuhammedKalkan** [comment]
@JeremyTheocharis Thanks for the offer. We are talking details about this ins discussions sections. We have collected money for the cert , just trying to find someone to buy and money transfer issues.

About a banner, i suppose you are referring to put something inside the app. In that case we are not modifying the source  code in any means. However, we can add a shout out inside README file of the repo.

Also signing and producing the binaries are automated. So we need to define cert as a secret inside this repo. Thats an easy thing to do, once we define cert owner as a collaborator.

**Comment by JeremyTheocharis** [comment]
> @JeremyTheocharis Thanks for the offer. We are talking details about this in discussions section. We have collected money for the cert , just trying to find someone to buy and money transfer issues.
> 
> About a banner, i suppose you are referring to put something inside the app. In that case we are not modifying the source code in any means. However, we can add a shout out inside README file of the repo.
> 
> Also signing and producing the binaries are automated. So we need to define cert as a secret inside this repo. Thats an easy thing to do, once we define cert owner as a collaborator.

Due to legal reasons, we would not be able to give the certificate to anyone else. If you want to do it automatically, then we need to ensure that we maintain full control over the signing process, which is likely only possible if we use as company our own repository. 

So two ideas:
1. We do the building and signing manually once per month for major releases
2. We clone your repository, give you write access to everything except the main branch, and setup the signing process for the main branch. With this we can ensure that nobody can sign in our company name.

If you are interested, my colleague can take over with the purchasing and setup process

**Comment by JeremyTheocharis** [comment]
We successfully purchased an EV Code Signing Certificate and will setup signed executable files in the upcoming days. These certificates are hardware bound (HSM), so we cannot setup automated code signing and need to do it manually. Please contact us to align on how we want to proceed here: www.umh.app

**Comment by JeremyTheocharis** [comment]
Hi together,

we successfully forked this repository and will offer signed binaries for Windows in the new repository: https://github.com/united-manufacturing-hub/UMHLens

Regards,
Jeremy

**Comment by MuhammedKalkan** [comment]
Hi @JeremyTheocharis ,

Sorry for the late response. Decision was to continue auto signing process and now it is also completed. 
Thank you for your time and offer
