### ISSUE TITLE
Lens Proxy Error, how to reset?

### ISSUE THREAD

**Issue by BarrieShieh** [MuhammedKalkan/OpenLens#41]
Hi,
I added an invalid proxy by accident, then the app wont start. How can I reset it? 

OS:  Mac
Version: 6.0.2 / 5.5.4

Thanks

Error message pop: 

<img width="372" alt="image" src="https://user-images.githubusercontent.com/13359539/190981983-fcdd15c5-b528-4453-a269-a26e54be58f7.png">

**Comment by jkroepke** [comment]
Please ask here:

https://github.com/lensapp/lens


@MuhammedKalkan we may should add an issue template which describes that we do not do Lens supports here.

**Comment by MuhammedKalkan** [comment]
Closing this one, since this is only build repo.
