### ISSUE TITLE
Latest version detection

### ISSUE THREAD

**Issue by jkroepke** [MuhammedKalkan/OpenLens#43]
The current workflow uses the official Lens auto-update mechanism (https://lens-binaries.s3.amazonaws.com/ide/latest-mac.yml) to detect the latest version.

Since this repo does not depend on official Lens builds, consider to switch the latest version detection based on the git tags on https://github.com/lensapp/lens/

e.g.

```bash
curl -sSfL https://github.com/lensapp/lens/releases.atom | grep -oP "(?<=<title>)v[^<]+" | head -n1
v6.1.0
```
requires gnu grep (may not work in mac os)

**Comment by mawatech** [comment]
You could also use the github API:

`curl -s https://api.github.com/repos/lensapp/lens/releases/latest | jq .tag_name | grep -oP "(\d+(:?\.\d+)+)" | head -n 1`

**Comment by mawatech** [comment]
Btw., seems they changed their version system, at least in the yml:

`curl -s https://lens-binaries.s3.amazonaws.com/ide/latest-mac.yml | grep -o "version:.*-latest"`
--> version: 2022.9.201328-latest

**Comment by jkroepke** [comment]
It seems like this need to be changes in anyways.

**Comment by MuhammedKalkan** [comment]
Yup, @jkroepke can you test these cli commands at your fork and  create a PR if successful

**Comment by jkroepke** [comment]
> You could also use the github API:
> 
> `curl -s https://api.github.com/repos/lensapp/lens/releases/latest | jq .tag_name | grep -oP "(\d+(:?\.\d+)+)" | head -n 1`

```
curl -s https://api.github.com/repos/lensapp/lens/releases/latest | jq -r '.tag_name[1:]'
```
