### ISSUE TITLE
The winget package does not install because the hash does not match.

### ISSUE THREAD

**Issue by thimo-seitz** [MuhammedKalkan/OpenLens#47]
The winget package does not install because the hash does not match to the installerfiles hash.

Failuremessage:
![grafik](https://user-images.githubusercontent.com/20231368/193203969-17052562-4098-4167-a956-2727fc2ddd70.png)

The manifest says: SHA256: 20b2e7420be69284d6cb35549a6507343da52d0ab0af4d72f0c74d7d6d63793b
![grafik](https://user-images.githubusercontent.com/20231368/193204809-a5a8fe08-366c-4a4f-9800-36c6f6b6b41a.png)

The calculatet sha256 is Sha256: 21228e88b8e1fa18f2a77ccd19e627c1238b79d3274c629e924bc2a3e218139d which is the same as statet in https://github.com/MuhammedKalkan/OpenLens/releases/download/v6.0.1/OpenLens-6.0.1.exe.sha256

**Comment by MuhammedKalkan** [comment]
Possible that hash is recalculated for a rebuild process. Please use force install or try newer versions which are available
