### ISSUE TITLE
Submodule causing errors in pipeline

### ISSUE THREAD

**Issue by disconn3ct** [MuhammedKalkan/OpenLens#5]
https://github.com/MuhammedKalkan/OpenLens/runs/6666587671?check_suite_focus=true#step:12:10 (Post-checkout, if it doesn't expand)

It is attempting to update the submodule and erroring out. The submodule should probably just be removed, based on the rest of the workflow.

**Comment by MuhammedKalkan** [comment]
Checkout action does not include submodules, default is false, but default post checkout tries to clean. Only gives a warning and does not affect builds. 

If there is a setting that we can turn it off, we can aswell do it, else can close this issue
