### ISSUE TITLE
GitHub Actions build is failing (6.2.0)

### ISSUE THREAD

**Issue by AndrewSav** [MuhammedKalkan/OpenLens#56]
Hello,

the badge seems to indicate a failed build for 6.2.0 and the actions has failed. And yet, magically we have the assets produced for 6.2.0 somehow. Can we get a clarification of what is going on here?

Thank you in advance!

**Comment by jetersen** [comment]
@AndrewSav only failed for MacOS, so ubuntu and linux assets are uploaded.
![image](https://user-images.githubusercontent.com/1661688/202613690-656c729d-411d-4572-852f-e962c8f4140a.png)
