### ISSUE TITLE
scoop install fails - bad hash value

### ISSUE THREAD

**Issue by jyurkiw** [MuhammedKalkan/OpenLens#57]
PS C:\Users\jyurk> scoop install openlens
Installing '7zip' (22.01) [64bit] from main bucket
7z2201-x64.msi (1.8 MB) [=====================================================================================] 100%
Checking hash of 7z2201-x64.msi ... ok.
Extracting 7z2201-x64.msi ... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\22.01
Creating shim for '7z'.
Creating shim for '7zFM'.
Creating shim for '7zG'.
Creating shortcut for 7-Zip (7zFM.exe)
Persisting Codecs
Persisting Formats
Running post_install script...
'7zip' (22.01) was installed successfully!
Notes
-----
Add 7-Zip as a context menu option by running: "C:\Users\jyurk\scoop\apps\7zip\current\install-context.reg"
Installing 'openlens' (6.2.0) [64bit] from extras bucket
OpenLens-6.2.0.exe (118.4 MB) [===============================================================================] 100%
Checking hash of OpenLens-6.2.0.exe ... ERROR Hash check failed!
App:         extras/openlens
URL:         https://github.com/MuhammedKalkan/OpenLens/releases/download/v6.2.0/OpenLens-6.2.0.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    ef53aec8269084ab07973ec3b4f0b8edc55dfdeb06d1d7c2bc53eaa923d15231
Actual:      c761f2db930d239d4e4175eadf07411325e90208d545e2c3515c887e1a5841bf

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=openlens%406.2.0%3a+hash+check+failed

**Comment by MuhammedKalkan** [comment]
building process restarted and seems scoop hash remains failed build hash.
Need to figure it out on scoop side or wait until new release version for scoop to work as expected.
Or just install this version by hand

**Comment by Re4zOon** [comment]
Why was this closed?
The issue still remains

**Comment by MuhammedKalkan** [comment]
Yes because there were new PRs and  binaries rebuilt. So please install by hand if you see hash value error or go to scoop side because that hash remains old and there is nothing to do here
