### ISSUE TITLE
brew - 6.2.1 SHA256 Mismatch arm64

### ISSUE THREAD

**Issue by dominicdejacomo** [MuhammedKalkan/OpenLens#64]
It looks like there is a SHA mismatch on the latest release for arm64 on brew

```
$ brew install --cask openlens
==> Downloading https://github.com/MuhammedKalkan/OpenLens/releases/download/v6.2.1/OpenLens-6.2.1-arm64.dmg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/497304002/d1486410-533a-4770-9dde-ccaee67e4ec9?X-Amz-Algorithm=AWS4-HMAC-SH
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 5aad8a7a5e7626921836f434dbdb0678c39f0fb41ea54c94e55417a639cb0e8c
  Actual: 52c287a264b8a0c3c10a3286a22d171e60d079e9c68a316df470b84075398071
    File: /Users/dominicdejacomo/Library/Caches/Homebrew/downloads/2bbef6d137fb3ad3b8a174914056bad468e4a1930e819cb7feb87e6b3de5afef--OpenLens-6.2.1-arm64.dmg
To retry an incomplete download, remove the file above.
```

**Comment by Grey2k** [comment]
Same for me

**Comment by gishmel** [comment]
I am getting this error and I am not on arm64 since this Macbook is from 2019; I wonder if it's broken for Mac OS in general then?

**Comment by MuhammedKalkan** [comment]
Install manually or wait for next release version, New PRs caused a rebuild and hashes are regenerated.

**Comment by stearz** [comment]
If you want to force homebrew to install it you can change the expected SHA:

`brew edit --cask openlens`

After this `brew install --cask openlens` is working.

Generally no good idea but as @MuhammedKalkan stated that it is a known issue and nothing has been compromised, it might be acceptable.
