### ISSUE TITLE
Question: automatic updates

### ISSUE THREAD

**Issue by waldner** [MuhammedKalkan/OpenLens#7]
When using this build, will the program check for automatic updates here or in the original Mirantis build, or somewhere else entirely?

**Comment by MuhammedKalkan** [comment]
No update check is performed. You need to manually install new release. 
Source code is untouched while building releases.

**Comment by waldner** [comment]
So is that check performed by some proprietary Mirantis plugin?

**Comment by MuhammedKalkan** [comment]
Yes, You can download 5.5.1 release and wait for a prompt to update or check network requests.

**Comment by waldner** [comment]
That's a shame, had it been an open source plugin it could have been included in the OpenLens build. Thanks!

**Comment by MuhammedKalkan** [comment]
Correction :Auto update can be configured and is now available with the new builds.

**Comment by waldner** [comment]
Great! Thanks!
