### ISSUE TITLE
Unable to install 6.2.5 - SHA256 Mistmatch

### ISSUE THREAD

**Issue by rajaie-sg** [MuhammedKalkan/OpenLens#80]
Trying to install 6.2.5 via brew results in the error below:

```
 /tmp brew install --cask openlens                                                                                                                   
==> Downloading https://github.com/MuhammedKalkan/OpenLens/releases/download/v6.2.5/OpenLens-6.2.5.dmg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/497304002/4be95a7a-dc85-4a7c-a3f5-fc23678ad9ae?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=A
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: edb95dd9c105ccdc5e64b94432175ad5812502eb8a1b36fa8a2bb6a2b1f3c00a
  Actual: c606162e05152a2f43b83f5d618a9085d184965fa2e571643d80be1b48664c2c
    File: /Users/rajaiealkorani/Library/Caches/Homebrew/downloads/86950502d2536e660c72e4119b1d034e7b944d44a5d779bd1c9211d6bdc959c8--OpenLens-6.2.5.dmg
To retry an incomplete download, remove the file above.
```

Is there a way to avoid this issue without manually updating the .sha via `brew edit`?

**Comment by netrifuge** [comment]
this looks related.  is this expected?

>winget install openlens
The `msstore` source requires that you view the following agreements before using.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
The source requires the current machine's 2-letter geographic region to be sent to the backend service to function properly (ex. "US").

Do you agree to all the source agreements terms?
[Y] Yes  [N] No: y
Found OpenLens [MuhammedKalkan.OpenLens] Version 6.2.5
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/MuhammedKalkan/OpenLens/releases/download/v6.2.5/OpenLens-6.2.5.exe
  ██████████████████████████████   118 MB /  118 MB
Installer hash does not match; to override this check use --force

**Comment by ludoo0d0a** [comment]
same behavior with scoop

**Comment by MuhammedKalkan** [comment]
Should be gone with new version

**Comment by alexrosenfeld10** [comment]
I'm seeing this trying to install:

```
❯ brew install openlens
Running `brew update --auto-update`...
==> Downloading https://github.com/MuhammedKalkan/OpenLens/releases/download/v6.
Already downloaded: /Users/me/Library/Caches/Homebrew/downloads/f5caaa3c636092e46b561e413b02675b87b693084585f0553ea4e849cd8571f7--OpenLens-6.3.0.dmg
Error: SHA256 mismatch
Expected: 2eb1848bb189041c4475054631a5b33a8ccd00c6eedbb74776b3dd1f54db7898
  Actual: a058d639903982fe8e06b9a820dee3745756524010dcfe13c482920f6ac5debf
    File: /Users/me/Library/Caches/Homebrew/downloads/f5caaa3c636092e46b561e413b02675b87b693084585f0553ea4e849cd8571f7--OpenLens-6.3.0.dmg
To retry an incomplete download, remove the file above.
```

If I delete the file and retry the same problem happens.
