### ISSUE TITLE
OpenLens 6.3.0 Blank UI

### ISSUE THREAD

**Issue by rajaie-sg** [MuhammedKalkan/OpenLens#81]
I upgraded from OpenLens 6.2.5 to 6.3.0 and now see a blank UI when I connect to any cluster

![image](https://user-images.githubusercontent.com/74200541/209192470-53f3796a-1f23-4ace-ae07-9dde61db6391.png)

I was not experiencing this issue with 6.2.5. I tried opening and closing the application multiple times, but the same issue persisted. Anyone else having similar issues?

**Comment by felipefda** [comment]
Same here

**Comment by ErezWeiss** [comment]
The only thing solved me for now is cmd+r

**Comment by mtomilov** [comment]
@ErezWeiss thank you for `cmd+r`, indeed helps

**Comment by ErezWeiss** [comment]
@mtomilov great!
Let us know if you solved it somehow

**Comment by rajaie-sg** [comment]
`cmd+r` made the UI come back, but it seems that I have to run it every time I open Lens. Another issue I discovered is that the "Exec into container" and "Logs" button is gone from Pods 
![image](https://user-images.githubusercontent.com/74200541/209200206-bba0187a-81bf-4dd3-ad3f-e07b37f72cc7.png)

**Comment by ErezWeiss** [comment]
Was it in the previous version?

**Comment by rajaie-sg** [comment]
Nope. With 6.2.5 I see the "Pod Logs" and "Pod Shell" and "Attach to Pod" buttons

**Comment by ErezWeiss** [comment]
seems related:
https://github.com/lensapp/lens/issues/1690

**Comment by ErezWeiss** [comment]
I've managed to install 6.2.5 and it seems to be working

**Comment by ErezWeiss** [comment]
`brew uninstall openlens`

`rm -rf ~/Library/Application Support/OpenLens`

`rm -rf ~/Library/Logs/OpenLens`

vi openlens.rb and paste this:
```
cask "openlens" do
  arch arm: "-arm64"

  version "6.2.5"
  sha256 arm:   "673a4ad49bb108bd1b995bf0d3eda971254ab6da4f54ad65f067208c8cde99db",
         intel: "e680ca5f0091663435696eff4da6666007d7bc8cb69078f56d1b7d7674cca296"

  url "https://github.com/MuhammedKalkan/OpenLens/releases/download/v#{version}/OpenLens-#{version}#{arch}.dmg"
  name "OpenLens"
  desc "Open source build of Lens Kubernetes IDE"
  homepage "https://github.com/MuhammedKalkan/OpenLens/"

  auto_updates true

  app "OpenLens.app"

  zap trash: [
    "~/Library/Application Support/OpenLens",
    "~/Library/Logs/OpenLens",
  ]
end
```

`brew install --cask openlens.rb`

**Comment by rajaie-sg** [comment]
> lensapp/lens#1690

Relevant issue https://github.com/lensapp/lens/issues/6823

**Comment by lingwooc** [comment]
https://github.com/lensapp/lens/issues/6819 Smells of revenue protection disguised as a technical fix. The arch package maintainer has got stuffed by this too. I expect a fork from 6.2.x will be the only solution.

**Comment by lukjaw** [comment]
yeah they killed it

https://github.com/lensapp/lens/issues/6823#issuecomment-1363736366

**Comment by jkroepke** [comment]
Reading PRs like https://github.com/lensapp/lens/pull/6722 feels like they also want to disable binaries at all.

**Comment by ErezWeiss** [comment]
Wow...
Seems like I will change from Lens

**Comment by stafot** [comment]
Also additionally to the above experience, I cannot change the sync files and folders option to have a specific config file. Always get reset to the default one.

**Comment by aleksfront** [comment]
> Also additionally to the above experience, I cannot change the sync files and folders option to have a specific config file. Always get reset to the default one.

https://github.com/lensapp/lens/issues/6834

**Comment by stafot** [comment]
With 6.2.5 dmg, things work as expected. Unfortunately ther is no brew support for installing this specific version.

**Comment by aleksfront** [comment]
@rajaie-sg Can you test if it's still an issue in latest `master`?

**Comment by nepomucen** [comment]
The good news is, that 6.4.0-alpha.0 fixes this issue and #6834 as well. 
Tested with local build on macOS Big Sur (M1 silicon)

**Comment by ErezWeiss** [comment]
> With 6.2.5 dmg, things work as expected. Unfortunately ther is no brew support for installing this specific version.

I've explained it above

**Comment by kaplanben** [comment]
> [ErezWeiss](/ErezWeiss)

@ErezWeiss, this only works for one time and the application is auto-updated to `6.3.0`. tried to `brew cu pin openlens` and other methods but can't get it to stop updating... any ideas?

**Comment by jkroepke** [comment]
Lens decide to make the update non toggleable.

**Comment by ErezWeiss** [comment]
Yeah, for me also..

**Comment by maurosaladino** [comment]
Hi, 
after installing version 6.2.5 it is possible to block updates change the permissions of the open-lens-updater folder:

`sudo chmod -R 000 ~/Library/Application Support/Caches/open-lens-updater/pending`

**Comment by maurosaladino** [comment]
> > [ErezWeiss](/ErezWeiss)
> 
> @ErezWeiss, this only works for one time and the application is auto-updated to `6.3.0`. tried to `brew cu pin openlens` and other methods but can't get it to stop updating... any ideas?

Hi,
after installing version 6.2.5 you can block updates by changing the permissions of the pending folder:

`sudo chmod -R 000 ~/Library/Application\ Support/Caches/open-lens-updater/pending`

**Comment by SergioSuarezDev** [comment]
same error here, on macOS 6.3.0

**Comment by kderck** [comment]
Same here

**Comment by djvs** [comment]
Just my 2c, this kind of thing is typically "fork in the road" time to break off from upstream.

**Comment by jkroepke** [comment]
@djvs feel free to fork

**Comment by djvs** [comment]
@jkroepke To fork off from the main Lens I mean, not to fork OpenLens, sorry.

**Comment by mombe090** [comment]
since i exec this command to block update, openlens is not launching anymore, no know how to fix this

**Comment by ErezWeiss** [comment]
> since i exec this command to block update, openlens is not launching anymore, no know how to fix this

working for me...

**Comment by maurosaladino** [comment]
> sudo chmod -R 000 ~/Library/Application\ Support/Caches/open-lens-updater/pending

Dude you can restore permission with this command:

`sudo chmod -R 755 ~/Library/Application\ Support/Caches/open-lens-updater/pending`

**Comment by mombe090** [comment]
> > sudo chmod -R 000 ~/Library/Application\ Support/Caches/open-lens-updater/pending
> 
> Dude you can restore permissions with this command:
> 
> `sudo chmod -R 755 ~/Library/Application\ Support/Caches/open-lens-updater/pending`

in tshoot i've deleted this folder, after reinstalling openlens, this folder not recreate ~/Library/Application Support/Caches/open-lens-updater/pending: No such file or directory

**Comment by maurosaladino** [comment]
> since i exec this command to block update, openlens is not launching anymore, no know how to fix this

I simply changed the permissions of the folder....if you can restore permissions with this command:

`sudo chmod -R 755 ~/Library/Application\ Support/Caches/open-lens-updater/pending`

**Comment by maurosaladino** [comment]
> > > sudo chmod -R 000 ~/Library/Application\ Support/Caches/open-lens-updater/pending
> > 
> > 
> > Dude you can restore permissions with this command:
> > `sudo chmod -R 755 ~/Library/Application\ Support/Caches/open-lens-updater/pending`
> 
> in tshoot i've deleted this folder, after reinstalling openlens, this folder not recreate ~/Library/Application Support/Caches/open-lens-updater/pending: No such file or directory

Could you explain better, I can't follow you...

**Comment by SergioSuarezDev** [comment]
Anyway I can't see the pods menu in 6.3.0 😅😅 it's an error?

**Comment by maurosaladino** [comment]
> Anyway I can't see the pods menu in 6.3.0 😅😅 it's an error?

Yes, it's a known issue, that's why we use 6.2.5 and block updates 😅

**Comment by jkroepke** [comment]
For 6.3.0, go to Extensions and install `@alebcay/openlens-node-pod-menu`, then pods menu are back.

**Comment by mombe090** [comment]
> > > > sudo chmod -R 000 ~/Library/Application\ Support/Caches/open-lens-updater/pending
> > > 
> > > 
> > > Dude you can restore permissions with this command:
> > > `sudo chmod -R 755 ~/Library/Application\ Support/Caches/open-lens-updater/pending`
> > 
> > 
> > in tshoot i've deleted this folder, after reinstalling openlens, this folder not recreate ~/Library/Application Support/Caches/open-lens-updater/pending: No such file or directory
> 
> Could you explain better, I can't follow you...

found how to fixed, brew uninstall didn't killed the lens process, so found it in monitor activity then kill it my self then workd, 6.2.5. Awesome thanks guys

**Comment by gsobczyk** [comment]
> > > [ErezWeiss](/ErezWeiss)
> > 
> > 
> > @ErezWeiss, this only works for one time and the application is auto-updated to `6.3.0`. tried to `brew cu pin openlens` and other methods but can't get it to stop updating... any ideas?
> 
> Hi, after installing version 6.2.5 you can block updates by changing the permissions of the pending folder:
> 
> `sudo chmod -R 000 ~/Library/Application\ Support/Caches/open-lens-updater/pending`

for Linux it's `~/.cache/open-lens-updater/pending` directory

**Comment by SergioSuarezDev** [comment]
> @alebcay/openlens-node-pod-menu

thank you!

**Comment by SergioSuarezDev** [comment]
> 



> For 6.3.0, go to Extensions and install `@alebcay/openlens-node-pod-menu`, then pods menu are back. Its way more easier then try to block to auto-update

thank you!

**Comment by wertone-gh** [comment]
I confirm I'm experiencing the same issue on ARM using 6.3.0. No issues on 6.2.5

**Comment by robross0606** [comment]
Seeing this here as well.  I can put 6.2.5 back on, but the darn thing keeps auto-updating to 6.3.0 and breaking again.

**Comment by MuhammedKalkan** [comment]
About disabling  the update can you all please ty this rather than some cli tricks 

https://github.com/MuhammedKalkan/OpenLens/issues/91#issuecomment-1373181989

**Comment by joshuamkite** [comment]
I think 6.3.0 release should be withdrawn from stable channel

**Comment by bczoma** [comment]
For anyone using 6.3.0 on Windows, it is CTRL+R that will show the cluster details. Thanks @ErezWeiss

**Comment by robross0606** [comment]
CTRL+R does not consistently work for me.  Moreover, sometimes when it shows the cluster, it shows corrupted or half-rendered data.  6.3.0 is just straight-up broken and should be yanked from stable channel.

**Comment by MuhammedKalkan** [comment]
Ok so that i understand. When i install extensions on 6.3.0 there is no issue. Are you guys talking about something else. Because i am not experiencing any missing behaviour

**Comment by bczoma** [comment]
In my case I have just started using  6.3.0 on Windows today. Using it as is, straight after installing without any add-ons/extensions. Only run into the blank UI issue but with the CTRL+R fix it has worked for me so far. However only used a subset of the functionality and haven't used it long enough to be able to tell if  6.3.0 is a good release or not.

**Comment by takeda** [comment]
@MuhammedKalkan the issue is the blank page when accessing cluster, as others mentioned cmd+r relates the screen, but even after that it doesn't look like it fully loads the information. When clicking on a pod there's no option to get a shell of it or see logs. There might be more things, but I didn't explore more, because the above already makes the product unusable.

Also an option to disable upgrade is absolutely needed. The recommendation given by others don't work. For example changing permissions on pending folder prevents OpenLens from starting.

Making the app (in OS X) read only, seems to work, but then open lens nags periodically to enter password.

**Comment by joshuamkite** [comment]
@MuhammedKalkan there's a screencap right at the top of this thread. That's what it looks like for me too. 

(In my opinion) Basic install of app should 'work', i.e.

As a Kubernetes administrator with a functioning `~/.kube/config` and current authentication:
- I can install OpenLens (via a supported mechanism on a supported platform)
- I can immediately run OpenLens, 
- I can immediately browse my cluster catalogue in OpenLens
- I can immediately explore my clusters in OpenLens

There should be no non-obvious steps required for basic functionality such as installing extensions or the `cmd+R`/`Ctrl+R` that I had to come here to find out about. Consider electron apps like:
- VSCode
- Google Chrome
- Slack

6.2.5 acheived this

**Comment by MuhammedKalkan** [comment]
I agree with you but currently Lens teams seems to prioritize getting OpenLens a package rather than an executable app. More than 3 weeks now, they have not published a new version. I feel next version will be just a package stripped to the bone.
We need to wait and see where this goes and then take action.

That being said, until then, auto update will not fetch 6.3.0 for now and you can revert to whatever version you like.

Keep in mind tho, this repo does not alter source code, so all that functionality needs a fork. That remains to be decided

**Comment by lukjaw** [comment]
> For 6.3.0, go to Extensions and install `@alebcay/openlens-node-pod-menu`, then pods menu are back. Its way more easier then try to block to auto-update
> 
> Checkout README.md in this repository, because its documented.

I am using this fix from @jkroepke (6.3.0) Windows 10 and its working fine so far.

**Comment by jkroepke** [comment]
> non-obvious steps required for basic functionality

@joshuamkite Please note that pod shell and pod logs are not longer part of the basic functionality. If you want this functionality, you have to install extensions.

**Comment by MuhammedKalkan** [comment]
Is this still an issue with the latest version ?

**Comment by MuhammedKalkan** [comment]
no i meant 6.4.0 alpha. There is nothing to be done for 6.3.0

**Comment by simonberger** [comment]
@MuhammedKalkan I tested the new version. The Pods entry is back, but I cannot access logs or start a shell of any Pod, just Editing or Deleting them.

**Comment by jkroepke** [comment]
@simonberger did you install the extension?

**Comment by simonberger** [comment]
@jkroepke No as I tested it on 6.3 but it was no working solution for me.

**Comment by jkroepke** [comment]
It feels like an upstream issue, I guess this issue can be closed here, since the error has nothing todo with the redistribution.

**Comment by pallasathena92** [comment]
> @simonberger did you install the extension? `@alebcay/openlens-node-pod-menu`

I tried to install extension '@alebcay/openlens-node-pod-menu' in Extensions in Openlens UI. But I got
"Failed to get registry information for extension: d: request to https://registry.npmjs.org/@alebcay/openlens-node-pod-menu failed, reason: unable to verify the first certificate"

**Comment by MuhammedKalkan** [comment]
That seems you have configured npm for a proxy or a vpn. Not relevant anything here

Either connect vpn or fix npm config

**Comment by pallasathena92** [comment]
> That seems you have configured npm for a proxy or a vpn. Not relevant anything here
> 
> Either connect vpn or fix npm config

thank you for responding. you are correct, my VPN made the install failed.

**Comment by hyprsnpr** [comment]
On version 6.3.0 or that latest alpha with @alebcay/openlens-node-pod-menu installed I still don't get any of the menus back. Any suggestions?

![image](https://user-images.githubusercontent.com/35845818/213511402-8e214477-4dcd-4f1b-bb75-3977102bc376.png)
![image](https://user-images.githubusercontent.com/35845818/213511537-11f2df24-838a-467d-b1f1-ac31113e25ee.png)

**Comment by joseph-skupniewicz-sp** [comment]
@hyprsnpr noticing this as well. Is this extension not working?

**Comment by hyprsnpr** [comment]
> @hyprsnpr noticing this as well. Is this extension not working?

It's def not working for me, it seems to be working for others so not sure why I'm broken. I'm windows where as a lot of the other examples I see is MacOS. I would have to think windows was tested though.

**Comment by joseph-skupniewicz-sp** [comment]
Updated cask for OpenLens v6.4.0-alpha4:

```# https://github.com/MuhammedKalkan/OpenLens/issues/81#issuecomment-1363225997
cask "openlens-6.4.0.4" do
  arch arm: "-arm64"

  version "6.4.0-alpha.4"
  sha256 arm:   "19ff657ec70114015382411b1a6ba8735148a6a0eefa7be29f0f61d50fd695c2",
         intel: "18643cfaa1461a15e4d07474491994ca17cdb17bb3dced28568e0bd223bff44c"

  url "https://github.com/MuhammedKalkan/OpenLens/releases/download/v#{version}/OpenLens-#{version}#{arch}.dmg"
  name "OpenLens"
  desc "Open source build of Lens Kubernetes IDE"
  homepage "https://github.com/MuhammedKalkan/OpenLens/"

  auto_updates true

  app "OpenLens.app"

  zap trash: [
    "~/Library/Application Support/OpenLens",
    "~/Library/Logs/OpenLens",
  ]
end
```

(renamed cask so as to not conflict/autoupdate with standard `openlens` cask)

**Comment by gnomeria** [comment]
> menu installed I still don't

where's this extension ui is located? I can't seem to be able to find it

**Comment by Stannislav** [comment]
For me the "Pods" item is missing from the Workloads menu:
![Screenshot 2023-02-14 at 17 17 29](https://user-images.githubusercontent.com/8017698/218795330-932f3a8a-5007-4a01-907d-56e699c6db01.png)

**Comment by bosch-oneux-1** [comment]
> Nope. With 6.2.5 I see the "Pod Logs" and "Pod Shell" and "Attach to Pod" buttons



> @MuhammedKalkan there's a screencap right at the top of this thread. That's what it looks like for me too.
> 
> (In my opinion) Basic install of app should 'work', i.e.
> 
> As a Kubernetes administrator with a functioning `~/.kube/config` and current authentication:
> 
> * I can install OpenLens (via a supported mechanism on a supported platform)
> * I can immediately run OpenLens,
> * I can immediately browse my cluster catalogue in OpenLens
> * I can immediately explore my clusters in OpenLens
> 
> There should be no non-obvious steps required for basic functionality such as installing extensions or the `cmd+R`/`Ctrl+R` that I had to come here to find out about. Consider electron apps like:
> 
> * VSCode
> * Google Chrome
> * Slack
> 
> 6.2.5 acheived this

@joshuamkite **Are you able to see Pod logs and Terminal button in 6.2.5 version?**
![image](https://github.com/MuhammedKalkan/OpenLens/assets/107052096/f7b56844-0944-44a8-b676-fd15c8b96458)

**Comment by kishorkk91** [comment]
> Nope. With 6.2.5 I see the "Pod Logs" and "Pod Shell" and "Attach to Pod" buttons
@rajaie-sg  Thank you for suggestion.
Windows 10 machine, I was able to resolve missing Pod shell/terminal and Log issue after installing **6.2.5** version.
https://github.com/MuhammedKalkan/OpenLens/releases/tag/v6.2.5

Uninstall existing OpenLens(if any) from "Add or remove programs"
If you have existing OpenLens then feel free to delete it.
Delete **C:\Users\YOURUSER\AppData\Roaming**
Delete **C:\Users\YOURUSER\AppData\Local\Programs**

Existing unwanted plugins can be removed also
Delete **C:\Users\YOURUSER\.k8slens**

Configure Kubectl and start using it.
