### ISSUE TITLE
Question: How to disable updates.... in the interim

### ISSUE THREAD

**Issue by tbertenshaw** [MuhammedKalkan/OpenLens#91]
On all my machines windows/mac i have pinned the version of open lens in `brew` or `chocolatey` to 6.25. 
 (Until we have a solution to the removal of  pod `logs` and `shell` buttons.)
 However it still periodically pulls updates and installs them if I restart my machine or lens. 

Is there a way to prevent updates being found as its just repulled and installed `6.3.0` ?

**Comment by NotANormalNerd** [comment]
Yeah, same question.

**Comment by biswanaths** [comment]
Just fyi, cmd+r still works on the updated 6.3.0. Version.

**Comment by MuhammedKalkan** [comment]
Have you guys just tried to change update channel ? From Stable to Alpha or Beta? That should work. Didnt try tho

![image](https://user-images.githubusercontent.com/19736494/210940351-7472a470-3ec6-4172-93b6-1b4d83456056.png)
