### ISSUE TITLE
pod details not clickable when pod shell is opened

### ISSUE THREAD

**Issue by cachila** [MuhammedKalkan/OpenLens#94]
I don't know if this should be reported here or at @alebcay/openlens-node-pod-menu.

The issue is that when a pod shell is opened, the pod details are not clickable in the highlighted area. (It seems like the `.KubeObjectDetails` z-index attribute is missing)

![image](https://user-images.githubusercontent.com/5391176/211310931-c96e63e7-6287-4aeb-ae22-5193aaced913.png)

**Comment by npasken** [comment]
seems like an extension issue - this is a build repo and probably should be asked in the extension project.

**Comment by alebcay** [comment]
This was an issue in Lens/OpenLens itself (https://github.com/lensapp/lens). The issue affects the bottom terminal pane in general, which is part of the base application.

As far as I can tell, this is fixed now in 6.4.0-alpha.1 and 6.4.0-alpha.2.
