### ISSUE TITLE
Exclude alpha version from auto-updates

### ISSUE THREAD

**Issue by jkroepke** [MuhammedKalkan/OpenLens#99]
Since, this repo now released alpha version, it should be useful to exclude them from auto-updates.

https://github.com/MuhammedKalkan/OpenLens/releases/Latest

**Comment by MuhammedKalkan** [comment]
Not sure, seems more stable than 6.3.0.

**Comment by MuhammedKalkan** [comment]
Ah and update files are not generated for some reason. So technically auto update is off
